(ns fuchi.methods.test-displacement-scorecard
  (:require [clojure.test :refer [deftest is]]
            [clojure.string :as str]
            [fuchi.methods.displacement-scorecard :as sc]
            [fuchi.methods.priority-stack :as pstack]
            [fuchi.methods.public-person :as pp]
            [fuchi.methods.displacement-l0-path :as dl0]))

#?(:cljs
   (def ^:private fs (js/require "node:fs")))

(defn- path-exists? [p]
  #?(:clj (.exists (java.io.File. (str p)))
     :cljs (.existsSync fs (str p))))

(defn- read-text [p]
  #?(:clj (slurp (str p))
     :cljs (.readFileSync fs (str p) "utf8")))

(deftest test-live-refuse-matrix
  (let [legs (sc/live-refuse-matrix)]
    (is (seq legs))
    (is (every? #(false? (:admissible %)) legs))
    (is (every? #(= 0 (:cash-usd-micros %)) legs))))

(deftest test-build-scorecard
  (let [body (sc/build)]
    (is (false? (:scorecard/live body)))
    (is (= 0 (:scorecard/cash-usd-micros body)))
    (is (= [] (:scorecard/score-surface body)))
    (is (true? (:scorecard/all-live-refused body)))
    ;; priority stack SSoT (1)L0 (2)disclosure (3)mitsuho embedded on scorecard
    (let [ps (:scorecard/priority-stack-offline body)]
      (is (map? ps))
      (is (nil? (:error ps)))
      (is (true? (pstack/assert-public-facts! ps))))
    (is (pos? (:scorecard/admissible-cohorts body)))
    (is (pos? (:scorecard/refused-cohorts body)))
    (is (pos? (:scorecard/enrolled-subjects body)))
    (is (pos? (:scorecard/committed-usd-micros-yr body)))
    (is (pos? (:scorecard/booked-entries body)))
    (is (pos? (:scorecard/tenure-subjects body)))
    (is (pos? (:scorecard/tenure-admissible-cohorts body)))
    (is (= "L6" (or (ffirst (:scorecard/tenure-stage-counts body))
                    (some-> (:scorecard/tenure-stage-counts body) keys first))))
       (is (pos? (:scorecard/gov-flowable-committed-usd-micros body)))
       (is (pos? (:scorecard/tenure-gov-flowable-committed-usd-micros body)))
       (is (pos? (:scorecard/tenure-gov-post-ratify-committed-usd-micros body)))
       (is (< (:scorecard/tenure-gov-flowable-committed-usd-micros body)
              (:scorecard/tenure-gov-post-ratify-committed-usd-micros body)))
       (is (pos? (:scorecard/tenure-disclosure-open body)))
       (is (zero? (:scorecard/tenure-disclosure-held body)))
       (is (pos? (:scorecard/mitsuho-r1-dry body)))
       (is (pos? (:scorecard/mitsuho-gated-refused body)))
       (is (zero? (:scorecard/mitsuho-produce-executed body)))
       (is (pos? (:scorecard/hikari-r1-dry body)))
       (is (pos? (:scorecard/hikari-gated-refused body)))
       (is (zero? (:scorecard/hikari-generate-executed body)))
       (is (pos? (:scorecard/care-r1-dry body)))
       (is (pos? (:scorecard/care-gated-refused body)))
       (is (zero? (:scorecard/care-delivery-executed body)))
       (is (pos? (:scorecard/housing-r1-dry body)))
       (is (pos? (:scorecard/housing-gated-refused body)))
       (is (zero? (:scorecard/housing-land-grant-executed body)))
       (is (pos? (:scorecard/housing-council-held body)))
       ;; displacement→L0 subject membranes (gated-receive/produce; default refuse)
       (is (pos? (:scorecard/displacement-membrane-subjects body)))
       (is (pos? (:scorecard/displacement-held-stress-subjects body)))
       (is (pos? (:scorecard/displacement-held-stress-ladder-refused body)))
       (is (= (:scorecard/displacement-held-stress-subjects body)
              (:scorecard/displacement-held-stress-ladder-refused body)))
       ;; tenure carries L0 held-stress; counted separately (no L4 double-count)
       (is (pos? (:scorecard/tenure-held-stress-subjects body)))
       (is (pos? (:scorecard/tenure-held-stress-ladder-refused body)))
       (is (pos? (:scorecard/tenure-held-stress-carried body)))
       (is (= (:scorecard/tenure-held-stress-subjects body)
              (:scorecard/tenure-held-stress-carried body)))
       (is (pos? (:scorecard/gov-held-stress-subjects body)))
       (is (pos? (:scorecard/gov-held-stress-ladder-refused body)))
       (is (pos? (:scorecard/tenure-gov-held-stress-subjects body)))
       (is (pos? (:scorecard/tenure-gov-held-stress-ladder-refused body)))
       (is (= (:scorecard/displacement-held-stress-subjects body)
              (:scorecard/gov-held-stress-subjects body)))
       (is (= (:scorecard/tenure-held-stress-subjects body)
              (:scorecard/tenure-gov-held-stress-subjects body)))
       (is (pos? (:scorecard/displacement-care-housing-full-chain-refused body)))
       (is (pos? (:scorecard/displacement-all-inkind-full-chain-refused body)))
       (is (pos? (:scorecard/displacement-all-seven-receive-membrane-refused body)))
       (is (pos? (:scorecard/displacement-liquidity-recv-refused body)))
       (is (pos? (:scorecard/displacement-food-recv-refused body)))
       (is (pos? (:scorecard/displacement-care-recv-refused body)))
       (is (pos? (:scorecard/displacement-housing-recv-refused body)))
       (is (pos? (:scorecard/tooling-r1-dry body)))
       (is (pos? (:scorecard/tooling-gated-refused body)))
       (is (zero? (:scorecard/tooling-fulfillment-executed body)))
       (is (pos? (:scorecard/compute-r1-dry body)))
       (is (pos? (:scorecard/compute-gated-refused body)))
       (is (zero? (:scorecard/compute-quota-executed body)))
       (is (pos? (:scorecard/liquidity-r1-dry body)))
       (is (pos? (:scorecard/liquidity-gated-refused body)))
       (is (zero? (:scorecard/liquidity-loan-executed body)))
       (is (pos? (:scorecard/liquidity-member-principal body)))
       (is (zero? (:scorecard/liquidity-cash-usd-micros body)))
       ;; R2 execute membrane (default refuse; never side-effects)
       (is (pos? (:scorecard/r2-status-count body)))
       (is (pos? (:scorecard/r2-refused body)))
       (is (zero? (:scorecard/r2-executed body)))
       (is (true? (:scorecard/all-r2-not-executed body)))
       (is (map? (:scorecard/r2-by-rail body)))
       (is (pos? (get-in body [:scorecard/r2-by-rail "food"] 0)))
       (let [l7 (:scorecard/l0-all-seven-enroll body)]
         (is (map? l7))
         (is (nil? (:error l7)))
         (is (= "enroll-with-all-seven-rails" (:api l7)))
         (is (= "open" (:disclosure-state l7)))
         (is (false? (:disclosure-held l7)))
         (is (true? (:entitlements-may-flow l7)))
         (is (true? (:all-inkind-produce-rails-full-chain-refused l7)))
         (is (true? (:liquidity-receive-full-chain-refused l7)))
         (is (true? (:all-seven-rails-receive-membrane-refused l7)))
         (is (true? (:liquidity-member-principal l7)))
         (is (false? (:liquidity-loan-executed l7)))
         (is (zero? (:liquidity-cash-usd-micros l7)))
         (is (false? (:land-grant-executed l7)))
         (is (false? (:live l7)))
         (is (zero? (:cash-usd-micros l7)))
         (is (= "open" (:continuity-final-state l7)))
         (is (pos? (:continuity-held-steps l7)))
         (is (= "advanced-offline" (:ladder-advance-phase l7)))
         (is (false? (:ladder-advance-refused l7))))
       (let [lh (:scorecard/l0-held-all-seven-enroll body)]
         (is (map? lh))
         (is (nil? (:error lh)))
         (is (= "held" (:disclosure-state lh)))
         (is (true? (:disclosure-held lh)))
         (is (false? (:entitlements-may-flow lh)))
         (is (true? (:all-seven-rails-receive-membrane-refused lh)))
         (is (true? (:ladder-advance-refused lh)))
         (is (= "refused" (:ladder-advance-phase lh)))
         (is (false? (:liquidity-loan-executed lh)))
         (is (false? (:live lh)))
         (is (zero? (:cash-usd-micros lh))))
       (let [ex (:scorecard/l0-exit-reaffirm body)]
         (is (map? ex))
         (is (nil? (:error ex)))
         (is (= "exit-suspended" (:exit-state ex)))
         (is (true? (:exit-suspended? ex)))
         (is (false? (:exit-entitlements-may-flow ex)))
         (is (true? (:exit-ladder-refused ex)))
         (is (= "open" (:reaffirm-state ex)))
         (is (false? (:reaffirm-exit-suspended? ex)))
         (is (true? (:reaffirm-entitlements-may-flow ex)))
         (is (false? (:reaffirm-ladder-refused ex)))
         (is (= "advanced-offline" (:reaffirm-ladder-phase ex)))
         (is (false? (:live ex)))
         (is (zero? (:cash-usd-micros ex))))
       (let [fl (:scorecard/l0-falsehood-lift body)]
         (is (map? fl))
         (is (nil? (:error fl)))
         (is (true? (:falsehood-held? fl)))
         (is (true? (:falsehood-ladder-refused fl)))
         (is (= "open" (:lift-state fl)))
         (is (true? (:lift-entitlements-may-flow fl)))
         (is (false? (:lift-ladder-refused fl)))
         (is (= "advanced-offline" (:lift-ladder-phase fl)))
         (is (false? (:live fl))))
       (let [cf (:scorecard/l0-care-first-mitsuho body)]
         (is (map? cf))
         (is (nil? (:error cf)))
         (is (= "open" (:disclosure-state cf)))
         (is (true? (:care-full-chain-refused cf)))
         (is (true? (:mitsuho-full-chain-refused cf)))
         (is (true? (:care-mitsuho-both-refused cf)))
         (is (= "advanced-offline" (:ladder-advance-phase cf)))
         (is (false? (:ladder-advance-refused cf)))
         (is (false? (:live cf)))
         (is (zero? (:cash-usd-micros cf)))
         (is (map? (:held-stress cf)))
         (is (true? (:held-stress-ladder-refused cf)))
         (is (true? (:held-stress-both-refused cf)))
         (is (true? (get-in cf [:held-stress :ladder-advance-refused]))))
       (let [ch (:scorecard/l0-care-first-hikari body)]
         (is (map? ch))
         (is (nil? (:error ch)))
         (is (true? (:care-hikari-both-refused ch)))
         (is (false? (:ladder-advance-refused ch)))
         (is (false? (:live ch)))
         (is (map? (:held-stress ch)))
         (is (true? (:held-stress-ladder-refused ch)))
         (is (true? (get-in ch [:held-stress :ladder-advance-refused]))))
       (let [cfh (:scorecard/l0-care-first-mitsuho-hikari body)]
         (is (map? cfh))
         (is (nil? (:error cfh)))
         (is (true? (:care-mitsuho-hikari-all-refused cfh)))
         (is (true? (:mitsuho-hikari-both-refused cfh)))
         (is (true? (:care-full-chain-refused cfh)))
         (is (true? (:mitsuho-full-chain-refused cfh)))
         (is (true? (:hikari-full-chain-refused cfh)))
         (is (false? (:ladder-advance-refused cfh)))
         (is (false? (:live cfh)))
         (is (zero? (:cash-usd-micros cfh)))
         (is (= [] (:score-surface cfh)))
         (is (map? (:held-stress cfh)))
         (is (true? (:held-stress-ladder-refused cfh)))
         (is (true? (:held-stress-all-refused cfh)))
         (is (true? (get-in cfh [:held-stress :ladder-advance-refused]))))
       (let [chs (:scorecard/l0-care-housing-first body)]
         (is (map? chs))
         (is (nil? (:error chs)))
         (is (true? (:care-housing-both-refused chs)))
         (is (false? (:land-grant-executed chs)))
         (is (false? (:ladder-advance-refused chs)))
         (is (false? (:live chs)))
         (is (zero? (:cash-usd-micros chs)))
         (is (map? (:held-stress chs)))
         (is (true? (:held-stress-ladder-refused chs)))
         (is (true? (:held-stress-both-refused chs)))
         (is (true? (get-in chs [:held-stress :ladder-advance-refused])))
         (is (false? (get-in chs [:held-stress :land-grant-executed]))))
       (let [mgs (:scorecard/l0-multi-gen-substrate body)]
         (is (map? mgs))
         (is (nil? (:error mgs)))
         (is (true? (:care-housing-mitsuho-hikari-all-refused mgs)))
         (is (true? (:care-housing-both-refused mgs)))
         (is (true? (:mitsuho-hikari-both-refused mgs)))
         (is (false? (:land-grant-executed mgs)))
         (is (false? (:ladder-advance-refused mgs)))
         (is (false? (:live mgs)))
         (is (zero? (:cash-usd-micros mgs)))
         (is (= [] (:score-surface mgs))))
       (let [fis (:scorecard/l0-full-inkind-substrate body)]
         (is (map? fis))
         (is (nil? (:error fis)))
         (is (true? (:all-inkind-produce-rails-full-chain-refused fis)))
         (is (true? (:tooling-compute-both-refused fis)))
         (is (false? (:land-grant-executed fis)))
         (is (false? (:fulfillment-executed fis)))
         (is (false? (:quota-executed fis)))
         (is (false? (:ladder-advance-refused fis)))
         (is (false? (:live fis)))
         (is (zero? (:cash-usd-micros fis)))
         (is (= [] (:score-surface fis))))
       (let [voc (:scorecard/l0-vocation-recovery body)]
         (is (map? voc))
         (is (nil? (:error voc)))
         (is (true? (:tooling-compute-both-refused voc)))
         (is (false? (:fulfillment-executed voc)))
         (is (false? (:quota-executed voc)))
         (is (false? (:ladder-advance-refused voc)))
         (is (false? (:live voc)))
         (is (zero? (:cash-usd-micros voc)))
         (is (= [] (:score-surface voc))))
       (let [liq (:scorecard/l0-liquidity-residual body)]
         (is (map? liq))
         (is (nil? (:error liq)))
         (is (true? (:liquidity-receive-full-chain-refused liq)))
         (is (true? (:liquidity-member-principal liq)))
         (is (false? (:liquidity-loan-executed liq)))
         (is (zero? (:liquidity-cash-usd-micros liq)))
         (is (false? (:ladder-advance-refused liq)))
         (is (false? (:live liq)))
         (is (zero? (:cash-usd-micros liq)))
         (is (= [] (:score-surface liq))))
       (let [a7s (:scorecard/l0-all-seven-substrate body)]
         (is (map? a7s))
         (is (nil? (:error a7s)))
         (is (true? (:all-inkind-produce-rails-full-chain-refused a7s)))
         (is (true? (:liquidity-receive-full-chain-refused a7s)))
         (is (true? (:all-seven-rails-receive-membrane-refused a7s)))
         (is (true? (:liquidity-member-principal a7s)))
         (is (false? (:liquidity-loan-executed a7s)))
         (is (false? (:land-grant-executed a7s)))
         (is (false? (:ladder-advance-refused a7s)))
         (is (false? (:live a7s)))
         (is (zero? (:cash-usd-micros a7s)))
         (is (= [] (:score-surface a7s))))
       (let [cat (:scorecard/l0-priority-path-catalog body)]
         (is (map? cat))
         (is (nil? (:error cat)))
         (is (pos? (or (:path-count cat) 0)))
         (is (some #(= "all-seven-substrate" (:id %)) (:paths cat)))
         (is (some #(= "vocation-recovery" (:id %)) (:paths cat)))
         (is (false? (:live cat)))
         (is (zero? (:cash-usd-micros cat)))
         (is (= [] (:score-surface cat))))
       (let [rc (:scorecard/rail-care-design body)]
         (is (map? rc))
         (is (nil? (:error rc)))
         (is (= "care-iyashi" (:rail-kind rc)))
         (is (= "care-housing-first-path" (:care-first-api-path rc)))
         (is (= 1 (:care-first-order-rank rc)))
         (is (true? (:multi-gen-first rc)))
         (is (false? (:care-delivery-executed rc)))
         (is (false? (:live rc)))
         (is (zero? (:cash-usd-micros rc)))
         (is (= [] (:score-surface rc))))
       (let [rho (:scorecard/rail-housing-design body)]
         (is (map? rho))
         (is (nil? (:error rho)))
         (is (= "housing-commons" (:rail-kind rho)))
         (is (= "care-housing-first-path" (:care-first-api-path rho)))
         (is (= 2 (:care-first-order-rank rho)))
         (is (= ["care"] (:care-first-before-rails rho)))
         (is (false? (:land-grant-executed rho)))
         (is (false? (:live rho)))
         (is (zero? (:cash-usd-micros rho)))
         (is (= [] (:score-surface rho))))
       (let [rm (:scorecard/rail-mitsuho-design body)]
         (is (map? rm))
         (is (nil? (:error rm)))
         (is (= "food-mitsuho" (:rail-kind rm)))
         (is (= "care-first-mitsuho-path" (:care-first-api-path rm)))
         (is (= ["care" "housing"] (:care-first-before-rails rm)))
         (is (false? (:live-produce rm)))
         (is (false? (:produce-executed rm)))
         (is (false? (:live rm)))
         (is (zero? (:cash-usd-micros rm)))
         (is (= [] (:score-surface rm)))
         (is (some #{"food-after-care-housing-for-mago-ko-substrate"} (:multi-gen-facts rm))))
       (let [rh (:scorecard/rail-hikari-design body)]
         (is (map? rh))
         (is (nil? (:error rh)))
         (is (= "energy-hikari" (:rail-kind rh)))
         (is (= "care-first-hikari-path" (:care-first-api-path rh)))
         (is (= ["care" "housing"] (:care-first-before-rails rh)))
         (is (false? (:live-produce rh)))
         (is (false? (:generate-executed rh)))
         (is (false? (:live rh)))
         (is (zero? (:cash-usd-micros rh)))
         (is (= [] (:score-surface rh))))
       (let [rt (:scorecard/rail-tooling-design body)]
         (is (map? rt))
         (is (nil? (:error rt)))
         (is (= "tooling-okaimono" (:rail-kind rt)))
         (is (= "vocation-recovery-path" (:care-first-api-path rt)))
         (is (true? (:vocation-recovery rt)))
         (is (false? (:fulfillment-executed rt)))
         (is (false? (:live rt)))
         (is (zero? (:cash-usd-micros rt))))
       (let [rco (:scorecard/rail-compute-design body)]
         (is (map? rco))
         (is (nil? (:error rco)))
         (is (= "compute-murakumo" (:rail-kind rco)))
         (is (= "vocation-recovery-path" (:care-first-api-path rco)))
         (is (true? (:vocation-recovery rco)))
         (is (false? (:quota-executed rco)))
         (is (false? (:live rco)))
         (is (zero? (:cash-usd-micros rco))))
       (let [rl (:scorecard/rail-liquidity-design body)]
         (is (map? rl))
         (is (nil? (:error rl)))
         (is (= "liquidity-warifu" (:rail-kind rl)))
         (is (= "liquidity-residual-path" (:care-first-api-path rl)))
         (is (true? (:member-principal rl)))
         (is (true? (:residual-rail rl)))
         (is (false? (:loan-executed rl)))
         (is (false? (:live rl)))
         (is (zero? (:cash-usd-micros rl))))
       (let [rcat (:scorecard/rail-design-catalog body)]
         (is (map? rcat))
         (is (nil? (:error rcat)))
         (is (= "fuchi.rail-design-catalog" (:catalog-id rcat)))
         (is (= 7 (:rail-count rcat)))
         (is (= 7 (:ok-count rcat)))
         (is (true? (:live-produce-never rcat)))
         (is (true? (:all-cash-zero rcat)))
         (is (true? (:all-live-false rcat)))
         (is (some #{"care-iyashi"} (:rail-kinds rcat)))
         (is (some #{"liquidity-warifu"} (:rail-kinds rcat)))
         (is (= 7 (count (:rails rcat))))
         (is (= sc/RAIL-DESIGN-ORDER (:order rcat)))
         (is (= ["care-iyashi" "housing-commons" "food-mitsuho" "energy-hikari"
                 "tooling-okaimono" "compute-murakumo" "liquidity-warifu"]
                (:rail-kinds rcat)))
         (is (false? (:live rcat)))
         (is (zero? (:cash-usd-micros rcat)))
         (is (= [] (:score-surface rcat))))
       ;; pure catalog reuses precomputed rails without re-calling design-public-facts
       (let [direct (sc/rail-design-catalog-fact
                     :rails [(:scorecard/rail-care-design body)
                             (:scorecard/rail-housing-design body)
                             (:scorecard/rail-mitsuho-design body)
                             (:scorecard/rail-hikari-design body)
                             (:scorecard/rail-tooling-design body)
                             (:scorecard/rail-compute-design body)
                             (:scorecard/rail-liquidity-design body)])]
         (is (= 7 (:rail-count direct)))
         (is (true? (:live-produce-never direct)))
         (is (= (:rail-kinds (:scorecard/rail-design-catalog body))
                (:rail-kinds direct))))
       (let [sp (:scorecard/ss-priority-path body)]
         (is (map? sp))
         (is (nil? (:error sp)))
         (is (= "L0" (:l0-stage sp)))
         (is (false? (:l0-published sp)))
         (is (= "open" (:l0-disclosure-state sp)))
         (is (false? (:l0-disclosure-held sp)))
         (is (true? (:l0-entitlements-may-flow sp)))
         (is (= "l0-enroll-offline" (:l0-path sp)))
         (is (= "L4" (:ladder-to sp)))
         (is (= "care" (:ladder-rails-hint-first sp)))
         (is (false? (:ladder-published sp)))
         (is (true? (:held-stress-ladder-refused sp)))
         ;; priority (3) mitsuho/hikari DESIGN facts on SS path scorecard projection
         (is (false? (:care-live-produce sp)))
         (is (false? (:housing-live-produce sp)))
         (is (= "care-housing-first-path" (:care-care-first-api-path sp)))
         (is (= "care-housing-first-path" (:housing-care-first-api-path sp)))
         (is (= 1 (:care-care-first-order-rank sp)))
         (is (= 2 (:housing-care-first-order-rank sp)))
         (is (= "care-iyashi" (:care-design-rail-kind sp)))
         (is (= "housing-commons" (:housing-design-rail-kind sp)))
         (is (false? (:mitsuho-live-produce sp)))
         (is (false? (:hikari-live-produce sp)))
         (is (= "care-first-mitsuho-path" (:mitsuho-care-first-api-path sp)))
         (is (= "care-first-hikari-path" (:hikari-care-first-api-path sp)))
         (is (= ["care" "housing"] (:mitsuho-care-first-before-rails sp)))
         (is (= "food-mitsuho" (:mitsuho-design-rail-kind sp)))
         (is (= "energy-hikari" (:hikari-design-rail-kind sp)))
         (is (false? (:tooling-live-produce sp)))
         (is (false? (:compute-live-produce sp)))
         (is (false? (:liquidity-live-produce sp)))
         (is (= "vocation-recovery-path" (:tooling-care-first-api-path sp)))
         (is (= "liquidity-residual-path" (:liquidity-care-first-api-path sp)))
         (is (= 7 (:all-seven-design-embed-count sp)))
         (is (true? (:all-seven-design-live-produce-never sp)))
         (is (= "L4" (:stage-sustenance-stage sp)))
         (is (= "care" (:stage-rails-first sp)))
         (is (= "housing" (:stage-rails-second sp)))
         (is (pos? (:stage-care-hours-floor-yr sp)))
         (is (false? (:stage-land-grant-executed sp)))
         (is (true? (:stage-r2-all-refused sp)))
         (is (true? (:stage-all-gated-refused sp)))
         (is (pos? (:stage-gated-count sp)))
         (is (false? (:stage-care-gated-admissible sp)))
         (is (false? (:stage-mitsuho-gated-admissible sp)))
         (is (false? (:mitsuho-gated-receive-admissible sp)))
         (is (false? (:hikari-gated-receive-admissible sp)))
         (is (true? (:mitsuho-hikari-receive-both-refused sp)))
         (is (false? (:care-gated-receive-admissible sp)))
         (is (true? (:care-mitsuho-hikari-receive-all-refused sp)))
         (is (false? (:mitsuho-gated-produce-admissible sp)))
         (is (false? (:hikari-gated-produce-admissible sp)))
         (is (true? (:mitsuho-hikari-produce-both-refused sp)))
         (is (true? (:mitsuho-hikari-full-chain-refused sp)))
         (is (false? (:care-gated-produce-admissible sp)))
         (is (true? (:care-mitsuho-hikari-produce-all-refused sp)))
         (is (true? (:care-mitsuho-hikari-full-chain-refused sp)))
         (is (false? (:housing-gated-receive-admissible sp)))
         (is (false? (:housing-gated-produce-admissible sp)))
         (is (true? (:housing-full-chain-refused sp)))
         (is (true? (:care-housing-mitsuho-hikari-receive-all-refused sp)))
         (is (true? (:care-housing-mitsuho-hikari-produce-all-refused sp)))
         (is (true? (:care-housing-mitsuho-hikari-full-chain-refused sp)))
         (is (false? (:tooling-gated-receive-admissible sp)))
         (is (false? (:tooling-gated-produce-admissible sp)))
         (is (true? (:tooling-full-chain-refused sp)))
         (is (false? (:compute-gated-receive-admissible sp)))
         (is (false? (:compute-gated-produce-admissible sp)))
         (is (true? (:compute-full-chain-refused sp)))
         (is (true? (:tooling-compute-full-chain-refused sp)))
         (is (true? (:all-inkind-produce-rails-full-chain-refused sp)))
         (is (false? (:liquidity-gated-receive-admissible sp)))
         (is (true? (:liquidity-receive-full-chain-refused sp)))
         (is (true? (:all-seven-rails-receive-membrane-refused sp)))
         (is (= "open" (:disclosure-state sp)))
         (is (true? (:entitlements-may-flow? sp)))
         (is (true? (:held-stress-held? sp)))
         (is (= 7 (:rails-gated-count sp)))
         (is (zero? (:rails-gated-admissible-count sp)))
         (is (true? (:all-rails-gated-refused sp)))
         (is (= 7 (:r2-status-count sp)))
         (is (zero? (:r2-executed-count sp)))
         (is (true? (:all-r2-not-executed sp)))
         (is (false? (:housing-land-grant-executed sp)))
         (is (false? (:live sp)))
         (is (zero? (:cash-usd-micros sp))))
       (is (map? (:scorecard/all-held-stress body)))
       (is (zero? (get-in body [:scorecard/all-held-stress :gov-flowable])))
       (is (pos? (get-in body [:scorecard/all-held-stress :open-gov-flowable])))
       (is (pos? (get-in body [:scorecard/all-held-stress :held-subjects])))
       (is (false? (get-in body [:scorecard/all-held-stress :live])))
       (is (= pp/PRIORITY-STACK (:scorecard/priority-stack body)))
       (let [md (sc/scorecard-md body)]
         (is (str/includes? md "scorecard"))
         (is (str/includes? md "wellbecoming"))
         (is (str/includes? md "tenure"))
         (is (str/includes? md "tenure gov flowable"))
         (is (str/includes? md "disclosure open/held"))
         (is (str/includes? md "mitsuho food"))
         (is (str/includes? md "hikari energy"))
         (is (str/includes? md "care-iyashi"))
         (is (str/includes? md "housing-commons"))
         (is (str/includes? md "displacement L0 membranes subjects"))
         (is (str/includes? md "all-seven receive-membrane"))
         (is (str/includes? md "displacement L0 liquidity residual receive-refused"))
         (is (str/includes? md "displacement L0 food/care/housing gated-recv-refused"))
         (is (str/includes? md "tooling-okaimono"))
         (is (str/includes? md "compute-murakumo"))
         (is (str/includes? md "liquidity-warifu"))
         (is (str/includes? md "R2 execute membrane"))
         (is (str/includes? md "all-r2-not-executed"))
         (is (str/includes? md "SS priority path"))
         (is (str/includes? md "L0 enroll all-seven rails"))
         (is (str/includes? md "enroll-with-all-seven-rails"))
         (is (str/includes? md "all-inkind / liquidity-receive / all-seven-membrane:"))
         (is (str/includes? md "continuity stress final/held-steps:"))
         (is (str/includes? md "L0 held all-seven"))
         (is (str/includes? md "disclosure stale stress"))
         (is (str/includes? md "L0 exit→re-affirm stress"))
         (is (str/includes? md "exit state/suspended/may-flow:"))
         (is (str/includes? md "re-affirm ladder phase/refused:"))
         (is (str/includes? md "L0 falsehood→lift-hold stress"))
         (is (str/includes? md "falsehood held/may-flow/ladder-refused:"))
         (is (str/includes? md "L0 care-first + mitsuho"))
         (is (str/includes? md "care/mitsuho full-chain/both-refused:"))
         (is (str/includes? md "care-first-api-path / before-rails:"))
         (is (str/includes? md "mitsuho-design rail-kind / live-produce / produce-executed:"))
         (is (str/includes? md "held-stress held/both-refused/ladder-refused:"))
         (is (str/includes? md "L0 care-first + hikari"))
         (is (str/includes? md "care/hikari full-chain/both-refused:"))
         (is (str/includes? md "hikari-design rail-kind / live-produce / generate-executed:"))
         (is (str/includes? md "L0 care-first + mitsuho + hikari"))
         (is (str/includes? md "care/mitsuho/hikari full-chain / all-refused:"))
         (is (str/includes? md "mitsuho/hikari design live-produce:"))
         (is (str/includes? md "held-stress held/all-refused/ladder-refused:"))
         (is (str/includes? md "care/housing DESIGN live-produce / care-first-api (孫/子 first):"))
         (is (str/includes? md "mitsuho/hikari DESIGN live-produce / care-first-api:"))
         (is (str/includes? md "tooling/compute/liquidity DESIGN live-produce / care-first-api:"))
         (is (str/includes? md "all-seven design embed-count / live-produce-never:"))
         (is (str/includes? md "mitsuho/hikari design-rail-kind:"))
         (is (str/includes? md "L0 care+housing multi-gen substrate"))
         (is (str/includes? md "land-grant-executed / ladder phase/refused:"))
         (is (str/includes? md "held-stress held/both-refused/ladder-refused/land-grant:"))
         (is (str/includes? md "displacement L0 held-stress subjects / ladder-refused:"))
         (is (str/includes? md "tenure held-stress subjects / ladder-refused / carried-from-L0:"))
         (is (str/includes? md "gov held-stress subjects / ladder-refused (L4 rows):"))
         (is (str/includes? md "tenure-gov held-stress subjects / ladder-refused:"))
         (is (str/includes? md "L0 multi-gen substrate + mitsuho+hikari"))
         (is (str/includes? md "care/housing/mitsuho/hikari full-chain / all-refused:"))
         (is (str/includes? md "held-stress held/all-refused/ladder-refused/land-grant:"))
         (is (str/includes? md "L0 full in-kind substrate"))
         (is (str/includes? md "six in-kind all-refused:"))
         (is (str/includes? md "held-stress held/all-refused/ladder-refused/land-grant/fulfillment/quota:"))
         (is (str/includes? md "L0 vocation recovery"))
         (is (str/includes? md "tooling/compute full-chain / both-refused:"))
         (is (str/includes? md "held-stress held/both-refused/ladder-refused/fulfillment/quota:"))
         (is (str/includes? md "L0 liquidity residual"))
         (is (str/includes? md "member-principal / loan-executed / cash-usd-micros:"))
         (is (str/includes? md "held-stress held/receive-refused/ladder-refused/loan/cash:"))
         (is (str/includes? md "L0 all-seven substrate"))
         (is (str/includes? md "all-inkind / liq-recv / all-seven-membrane:"))
         (is (str/includes? md "held-stress held/membrane/ladder-refused/loan/land-grant:"))
         (is (str/includes? md "L0 offline priority path catalog"))
         (is (str/includes? md "path-ids:"))
         (is (str/includes? md "held-stress-embed-count:"))
         (is (str/includes? md "held-stress-embed-all"))
         (is (str/includes? md "rail-care-iyashi DESIGN"))
         (is (str/includes? md "care-is-wellbecoming-substrate"))
         (is (str/includes? md "rail-housing-commons DESIGN"))
         (is (str/includes? md "land-grant-executed / live-produce:"))
         (is (str/includes? md "rail-mitsuho DESIGN"))
         (is (str/includes? md "care-first-mitsuho-path"))
         (is (str/includes? md "food-after-care-housing-for-mago-ko-substrate"))
         (is (str/includes? md "rail-hikari DESIGN"))
         (is (str/includes? md "care-first-hikari-path"))
         (is (str/includes? md "live-produce / produce-executed:"))
         (is (str/includes? md "live-produce / generate-executed:"))
         (is (str/includes? md "rail-tooling-okaimono DESIGN"))
         (is (str/includes? md "vocation-recovery-path"))
         (is (str/includes? md "rail-compute-murakumo DESIGN"))
         (is (str/includes? md "rail-liquidity-warifu DESIGN"))
         (is (str/includes? md "member-principal / loan-executed / cash:"))
         (is (str/includes? md "rail DESIGN catalog (all-seven discovery)"))
         (is (str/includes? md "live-produce-never / all-cash-zero / all-live-false:"))
         (is (str/includes? md "care-iyashi"))
         (is (str/includes? md "L0 enroll disclosure open/held/may-flow:"))
         (is (str/includes? md "ladder offline:"))
         (is (str/includes? md "rails-hint-first="))
         (is (str/includes? md "stage_sustenance:"))
         (is (str/includes? md "r2-all-refused="))
         (is (str/includes? md "gated-all-refused="))
         (is (str/includes? md "stage care/mitsuho/hikari gated-admissible:"))
         (is (str/includes? md "mitsuho/hikari gated-receive admissible/both-refused:"))
         (is (str/includes? md "care-iyashi gated-receive (孫/子) admissible/all-three-refused:"))
         (is (str/includes? md "mitsuho/hikari gated-produce admissible/both/full-chain-refused:"))
         (is (str/includes? md "care gated-produce (孫/子) admissible/produce-all/full-chain:"))
         (is (str/includes? md "housing gated-receive/produce (孫/子) admissible/full-chain:"))
         (is (str/includes? md "care+housing+food+energy full-chain-refused:"))
         (is (str/includes? md "tooling/compute gated-receive/produce admissible/full-chain:"))
         (is (str/includes? md "tooling+compute full-chain / all-inkind-produce-rails full-chain:"))
         (is (str/includes? md "liquidity gated-receive admissible/receive-full-chain:"))
         (is (str/includes? md "all-seven-rails receive-membrane refused:"))
         (is (str/includes? md "all-rails-gated-refused"))
         (is (str/includes? md "member-principal"))
         (is (str/includes? md "All-disclosure-held stress"))
         (is (str/includes? md "land-grant-executed"))
         (is (str/includes? md "all live legs refused"))
         (is (not (str/includes? md "| rank |"))))))

(deftest test-build-from-bare-l0-batch-attaches-tenure
  (let [bare (dl0/run-default-seed :max-slots 2 :climb-steps 4)
        body (sc/build bare)]
    (is (nil? (some :tenure-phase (:packages bare))))
    (is (pos? (:scorecard/tenure-subjects body)))
    (is (pos? (:scorecard/tenure-admissible-cohorts body)))
    (is (pos? (:scorecard/tenure-gov-flowable-committed-usd-micros body)))
    (is (false? (:scorecard/live body)))
    (is (= 0 (:scorecard/cash-usd-micros body)))))

(deftest test-write-scorecard
  (let [paths (sc/write-scorecard!)]
    (is (path-exists? (:md paths)))
    (is (path-exists? (:edn paths)))
    (is (true? (:all-live-refused paths)))
    (is (false? (:live paths)))
    (is (pos? (:tenure-subjects paths)))
    (is (str/includes? (read-text (:md paths)) "No personal scores"))))
