(ns fuchi.methods.test-pages-deploy
  (:require [clojure.test :refer [deftest is]]
            [clojure.string :as str]
            [fuchi.methods.pages-deploy :as dep]
            [fuchi.methods.public-person :as pp]
            ))

#?(:cljs
   (def ^:private fs (js/require "node:fs")))

(defn- path-exists? [p]
  #?(:clj (.exists (java.io.File. (str p)))
     :cljs (.existsSync fs (str p))))

(defn- read-text [p]
  #?(:clj (slurp (str p))
     :cljs (.readFileSync fs (str p) "utf8")))

(deftest test-default-refuse
  (let [st (dep/default-refuse-status {})
        refu (dep/refuse-deploy {})
        rb (:operator-runbook refu)]
    (is (false? (get st "admissible")))
    (is (= :refused (:phase refu)))
    (is (false? (:deployed refu)))
    (is (false? (:authorized-to-deploy refu)))
    (is (true? (:package-ready refu)))
    (is (false? (:wrangler-invoked refu)))
    (is (false? (:live refu)))
    (is (= 0 (:cash-usd-micros refu)))
    (is (map? rb))
    (is (false? (:scaffold-invokes-wrangler rb)))
    (is (seq (:steps rb)))
    (pp/assert-no-public-scores! (dissoc refu :operator-runbook))
    (pp/assert-no-public-scores! rb)))

(deftest test-operator-runbook-facts
  (let [rb (dep/operator-runbook-facts)]
    (is (= "FUCHI_ALLOW_PAGES_DEPLOY" (:flag rb)))
    (is (false? (:scaffold-invokes-wrangler rb)))
    (is (false? (:scaffold-invokes-cloudflare-api rb)))
    (is (false? (:deployed rb)))
    (is (false? (:live-disbursement rb)))
    (is (= 0 (:cash-usd-micros rb)))
    (is (seq (:steps rb)))
    (pp/assert-no-public-scores! rb)))

(deftest test-gated-plan-not-deployed
  (let [plan (dep/gated-deploy-plan
              {:operator-did "did:op:pages" :project-name "fuchi-public-surface"}
              :env {"FUCHI_ALLOW_PAGES_DEPLOY" "1"})]
    (is (= :gated-deploy-plan (:phase plan)))
    (is (true? (:authorized-to-deploy plan)))
    (is (true? (:package-ready plan)))
    (is (false? (:deployed plan)))
    (is (false? (:wrangler-invoked plan)))
    (is (false? (:cloudflare-api-invoked plan)))
    (is (map? (:operator-runbook plan)))
    (pp/assert-no-public-scores! (dissoc plan :operator-runbook))))

(deftest test-deploy-or-refuse-no-flag
  (let [out (dep/deploy-or-refuse {:operator-did "did:op:x"} :env {})]
    (is (= :refused (:phase out)))
    (is (false? (:deployed out)))))

(deftest test-gated-deploy-status-default-refuse-no-throw
  (let [st (dep/gated-deploy-status {:operator-did "did:op:x"} :env {})]
    (is (= :refused (:phase st)))
    (is (false? (:admissible st)))
    (is (false? (:deployed st)))
    (is (false? (:wrangler-invoked st)))
    (is (false? (:cloudflare-api-invoked st)))
    (is (false? (:live st)))
    (is (= 0 (:cash-usd-micros st)))
    (pp/assert-no-public-scores! st)))

(deftest test-gated-deploy-status-plan-with-flag
  (let [st (dep/gated-deploy-status
            {:operator-did "did:op:pages" :project-name "fuchi-public-surface"}
            :env {"FUCHI_ALLOW_PAGES_DEPLOY" "1"})]
    (is (= :gated-deploy-plan (:phase st)))
    (is (true? (:admissible st)))
    (is (true? (:authorized-to-deploy st)))
    (is (false? (:deployed st)))
    (is (false? (:wrangler-invoked st)))
    (is (false? (:live st)))
    (is (= 0 (:cash-usd-micros st)))
    (pp/assert-no-public-scores! st)))

(deftest test-write-deploy-package
  (let [pkg (dep/write-deploy-package! {})
        st (:deploy-status pkg)
        rb-path (:deploy-runbook pkg)]
    (is (path-exists? (:index pkg)))
    (is (path-exists? (:wrangler pkg)))
    (is (path-exists? rb-path))
    (is (path-exists? "public/priority-stack-offline.edn"))
    (is (some #{"priority-stack-offline.edn"} (:static-files st)))
    (is (false? (:deployed pkg)))
    (is (false? (:wrangler-invoked pkg)))
    (is (true? (:package-ready pkg)))
    (is (false? (:live pkg)))
    (is (= 0 (:cash-usd-micros pkg)))
    (is (= :refused (:phase st)))
    (is (false? (:authorized-to-deploy st)))
    (is (map? (:operator-runbook st)))
    (is (map? (:audit-snapshot st)))
    (is (false? (boolean (get-in st [:audit-snapshot :any-land-grant-executed?]))))
    (is (zero? (or (get-in st [:audit-snapshot :last-run-housing-land-grant-executed]) 0)))
    (is (false? (get-in st [:audit-snapshot :live])))
    (is (true? (boolean (:ss-all-seven-design-live-produce-never pkg true))))
    (let [snap (:audit-snapshot st)]
      (when (pos? (or (:runs snap) 0))
        (is (contains? snap :last-run-ss-stage-all-gated-refused))
        (is (contains? snap :last-run-ss-stage-care-gated-admissible))
        (is (false? (boolean (:last-run-ss-stage-land-grant-executed snap))))
        (is (contains? snap :last-run-ss-housing-full-chain-refused))
        (is (contains? snap :last-run-ss-tooling-full-chain-refused))
        (is (contains? snap :last-run-ss-compute-full-chain-refused))
        (is (contains? snap :last-run-ss-all-inkind-produce-rails-full-chain-refused))
        (is (contains? snap :last-run-ss-liquidity-receive-full-chain-refused))
        (is (contains? snap :last-run-ss-all-seven-rails-receive-membrane-refused))
        (is (contains? snap :last-run-ss-l0-disclosure-state))
        (is (contains? snap :last-run-ss-l0-path))
        (is (contains? snap :last-run-l0-all-seven-membrane-refused))
        (is (contains? snap :last-run-l0-all-seven-liquidity-loan-executed))
        (is (contains? snap :last-run-l0-all-seven-continuity-final-state))
        (is (contains? snap :last-run-l0-all-seven-ladder-advance-phase))
        (is (contains? snap :last-run-l0-held-all-seven-membrane-refused))
        (is (contains? snap :last-run-l0-held-all-seven-ladder-advance-refused))
        (is (contains? snap :last-run-l0-exit-state))
        (is (contains? snap :last-run-l0-reaffirm-ladder-phase))
        (is (contains? snap :last-run-l0-falsehood-held))
        (is (contains? snap :last-run-l0-lift-ladder-phase))
        (is (contains? snap :last-run-l0-care-first-both-refused))
        (is (contains? snap :last-run-l0-care-first-hikari-both-refused))
           (is (contains? snap :last-run-l0-care-first-mitsuho-hikari-all-refused))
           (is (contains? snap :last-run-l0-care-housing-both-refused))
           (is (contains? snap :last-run-l0-care-housing-held-stress-ladder-refused))
           (is (contains? snap :last-run-l0-multi-gen-substrate-all-refused))
           (is (contains? snap :last-run-l0-multi-gen-substrate-held-stress-ladder-refused))
           (is (contains? snap :last-run-l0-full-inkind-all-refused))
           (is (contains? snap :last-run-l0-full-inkind-held-stress-ladder-refused))
           (is (contains? snap :last-run-l0-vocation-recovery-both-refused))
           (is (contains? snap :last-run-l0-vocation-recovery-held-stress-ladder-refused))
           (is (contains? snap :last-run-l0-liquidity-residual-receive-refused))
           (is (contains? snap :last-run-l0-liquidity-residual-held-stress-ladder-refused))
           (is (contains? snap :last-run-l0-all-seven-substrate-membrane-refused))
           (is (contains? snap :last-run-l0-all-seven-substrate-held-stress-ladder-refused))
           (is (contains? snap :last-run-l0-priority-path-count))
           (is (contains? snap :last-run-l0-priority-held-stress-embed-count))
           (is (contains? snap :last-run-l0-priority-held-stress-embed-all))
           (is (contains? snap :last-run-rail-design-rail-count))
           (is (contains? snap :last-run-rail-design-ok-count))
           (is (contains? snap :last-run-rail-design-live-produce-never))
           (is (contains? snap :last-run-rail-design-all-seven))
           (is (contains? snap :last-run-ss-mitsuho-live-produce))
           (is (contains? snap :last-run-l0-care-first-mitsuho-live-produce))
           (is (contains? snap :last-run-l0-care-first-hikari-live-produce))
           (is (contains? snap :last-run-displacement-membrane-subjects))
           (is (contains? snap :last-run-displacement-held-stress-subjects))
           (is (contains? snap :last-run-displacement-held-stress-ladder-refused))
           (is (contains? snap :last-run-tenure-held-stress-subjects))
           (is (contains? snap :last-run-tenure-held-stress-ladder-refused))
           (is (contains? snap :last-run-tenure-held-stress-carried))
           (is (contains? snap :last-run-gov-held-stress-subjects))
           (is (contains? snap :last-run-gov-held-stress-ladder-refused))
           (is (contains? snap :last-run-tenure-gov-held-stress-subjects))
           (is (contains? snap :last-run-tenure-gov-held-stress-ladder-refused))
           (is (contains? snap :last-run-displacement-all-seven-receive-membrane-refused))
           (is (contains? snap :last-run-displacement-liquidity-recv-refused))
           (when (pos? (or (:last-run-ss-stage-gated-count snap) 0))
             (is (true? (boolean (:last-run-ss-stage-all-gated-refused snap))))
             (is (false? (boolean (:last-run-ss-stage-care-gated-admissible snap))))
             (is (false? (boolean (:last-run-ss-stage-mitsuho-gated-admissible snap))))
             (is (false? (boolean (:last-run-ss-stage-hikari-gated-admissible snap))))
             ;; when pipeline has full rail path, membrane aggregates refuse
             (when (contains? snap :last-run-ss-housing-full-chain-refused)
               (is (true? (boolean (:last-run-ss-housing-full-chain-refused snap)))))
             (when (contains? snap :last-run-ss-all-seven-rails-receive-membrane-refused)
               (is (true? (boolean (:last-run-ss-all-seven-rails-receive-membrane-refused snap))))))))
    (let [html (read-text (:index pkg))
          readme (read-text "public/README.md")
          rb (read-string (read-text rb-path))]
      (is (str/includes? html "public surface"))
      (is (str/includes? html "wellbecoming"))
      (is (str/includes? html "Displacement → L0"))
      (is (str/includes? html "plan-only"))
      (is (str/includes? html "wrangler-invoked="))
      (is (str/includes? readme "out-of-band"))
      (is (str/includes? readme "Operator runbook"))
      (is (str/includes? readme "all-inkind-produce-rails"))
      (is (str/includes? readme "all-seven-rails"))
      (is (str/includes? readme "L0 enroll disclosure"))
      (is (str/includes? readme "L0 all-seven membrane"))
      (is (str/includes? readme "L0 all-seven continuity/ladder"))
      (is (str/includes? readme "L0 held all-seven membrane"))
      (is (str/includes? readme "L0 exit→re-affirm"))
      (is (str/includes? readme "L0 falsehood→lift"))
      (is (str/includes? readme "L0 care-first+mitsuho"))
      (is (str/includes? readme "L0 care-first+hikari"))
      (is (str/includes? readme "L0 care-first+mitsuho+hikari"))
      (is (str/includes? readme "L0 care+housing both-refused"))
      (is (str/includes? readme "L0 multi-gen substrate"))
      (is (str/includes? readme "L0 full-inkind six-rails"))
      (is (str/includes? readme "L0 vocation recovery"))
      (is (str/includes? readme "L0 liquidity residual"))
      (is (str/includes? readme "L0 all-seven substrate"))
      (is (str/includes? readme "rail DESIGN catalog"))
      (is (str/includes? readme "live-produce-never"))
      (is (str/includes? readme "care-first DESIGN mitsuho/hikari live-produce"))
      (is (str/includes? readme "displacement L0 membranes"))
      (is (false? (:scaffold-invokes-wrangler rb)))
      (is (not (re-find #"(?i)priority-rank" html))))))
