(ns fuchi.methods.test-public-surface-report
  "Public surface report tests — portable under nbb and bb (ADR-2607173000)."
  (:require [clojure.test :refer [deftest is]]
            [clojure.string :as str]
            [fuchi.methods.public-surface-report :as rep]
            [fuchi.methods.priority-stack :as pstack]
            [fuchi.methods.public-person :as pp]
            [fuchi.methods.edn :as edn]))

#?(:cljs
   (def ^:private fs (js/require "node:fs")))

(defn- seed []
  (edn/load-data "seed-sustenance-graph.kotoba.edn"))

(defn- path-exists? [p]
  #?(:clj (.exists (java.io.File. (str p)))
     :cljs (.existsSync fs (str p))))

(defn- read-text [p]
  #?(:clj (slurp (str p))
     :cljs (.readFileSync fs (str p) "utf8")))

(deftest test-seed-facts-no-scores
  (let [facts (rep/seed-public-facts (seed))]
    (is (seq facts))
    (doseq [f facts]
      (is (nil? (:priority-rank f)))
      (is (= [] (:score-surface f)))
      (pp/assert-no-public-scores! f))))

(deftest test-report-md-has-no-rank-columns
  (let [md (rep/report-md (seed) :include-l0-demo true :include-itonami true)]
    (is (str/includes? md "public surface"))
    (is (str/includes? md "wellbecoming"))
    (is (str/includes? md "Dry floor facts"))
    (is (str/includes? md "care-h"))
    (is (not (str/includes? md "| rank |")))
    (is (not (re-find #"(?i)\| *percentile *\|" md)))
    (is (str/includes? md "No personal scores"))
    (is (str/includes? md "L0 demo"))))

(deftest test-report-edn-invariants
  (let [body (rep/report-edn (seed) :include-l0-demo true :include-itonami true)]
    (is (= [] (:report/score-surface body)))
    (is (= 0 (:report/cash-usd-micros body)))
    (is (false? (:report/live body)))
    (is (= pp/PRIORITY-STACK (:report/priority-stack body)))
    (is (seq (:report/rail-packages body)))
    (is (seq (:report/displacement body)))
    (is (= 2 (get-in body [:report/displacement-summary :displacement-events])))
    (let [abel (first (filter #(str/includes? (str (:did %)) "abel")
                              (:report/rail-packages body)))]
      (is (some? abel))
      (is (or (nil? (:food-floor abel))
              (false? (get-in abel [:food-floor :produce-executed]))))
      (when-let [ff (:food-floor abel)]
        (is (pos? (:kcal-floor-yr ff))))
      (when-let [ef (:energy-floor abel)]
        (is (pos? (:kwh-floor-yr ef))))
      (is (= 0 (:cash-usd-micros abel)))
      (is (= [] (:score-surface abel))))
    (is (seq (:report/itonami-displacement body)))
    (is (= 4 (count (:report/itonami-displacement body))))
    (is (map? (:report/displacement-l0 body)))
    (is (pos? (get-in body [:report/displacement-l0 :admissible-cohorts] 0)))
    (is (pos? (get-in body [:report/displacement-l0 :refused-cohorts] 0)))
    (is (= 0 (get-in body [:report/displacement-l0 :cash-usd-micros])))
    (is (= [] (get-in body [:report/displacement-l0 :score-surface])))
    (is (pos? (get-in body [:report/displacement-l0 :membrane-subjects] 0)))
    (is (pos? (get-in body [:report/displacement-l0 :all-seven-receive-membrane-refused-n] 0)))
    (is (pos? (get-in body [:report/displacement-l0 :liquidity-recv-refused-n] 0)))
    (is (true? (get-in body [:report/displacement-scorecard :scorecard/all-live-refused])))
    (is (pos? (get-in body [:report/displacement-scorecard :scorecard/enrolled-subjects] 0)))
    (let [ps (:report/priority-stack-offline body)]
      (is (map? ps))
      (is (nil? (:error ps)))
      (is (true? (pstack/assert-public-facts! ps))))
    (is (pos? (get-in body [:report/displacement-scorecard :scorecard/liquidity-r1-dry] 0)))
    (is (pos? (get-in body [:report/displacement-scorecard :scorecard/liquidity-member-principal] 0)))
    (is (zero? (get-in body [:report/displacement-scorecard :scorecard/liquidity-loan-executed] 0)))
    (is (zero? (get-in body [:report/displacement-scorecard :scorecard/liquidity-cash-usd-micros] 0)))
    (is (pos? (get-in body [:report/displacement-scorecard
                            :scorecard/displacement-all-seven-receive-membrane-refused] 0)))
    (is (zero? (get-in body [:report/displacement-scorecard :scorecard/housing-land-grant-executed] 0)))
    (is (map? (get-in body [:report/displacement-scorecard :scorecard/all-held-stress])))))

(deftest test-write-report
  (let [paths (rep/write-report!)]
    (is (path-exists? (:md paths)))
    (is (path-exists? (:edn paths)))
    (is (path-exists? (:html paths)))
    (is (str/includes? (read-text (:md paths)) "facts only"))
    (is (str/includes? (read-text (:html paths)) "Displacement"))
    (is (not (re-find #"(?i)\| *rank *\|" (read-text (:html paths)))))))

(deftest test-public-md-html-liquidity-and-rails
  (let [md (rep/report-md (seed) :include-l0-demo true :include-itonami true)
        html (rep/report-html (seed) :include-l0-demo true :include-itonami true)
        body (rep/report-edn (seed) :include-l0-demo true :include-itonami true)]
       (is (str/includes? md "liquidity-warifu"))
       (is (str/includes? md "member-principal"))
       (is (str/includes? md "All-disclosure-held stress"))
       (is (str/includes? md "housing-commons"))
       (is (str/includes? md "care-iyashi"))
       (is (str/includes? md "disc-o/h"))
       (is (str/includes? md "disclosure-open="))
       (is (str/includes? md "| g2 |"))
       (is (str/includes? md "| earmark |"))
       (is (str/includes? md "earmark-total="))
       (is (str/includes? md "committed-flowable-total="))
       (is (str/includes? md "committed-full-total="))
       (is (str/includes? md "L0 membranes subjects/all-inkind/all-seven/liq-recv-refused="))
       (is (str/includes? html "L0 membranes subjects/all-inkind/all-seven/liq-recv="))
       (is (str/includes? html "displacement L0 membranes subjects"))
       (is (str/includes? md "tenure-subjects="))
       (is (str/includes? md "tenure-committed-flow="))
       (is (str/includes? md "ten-flow"))
       (is (str/includes? md "L4-post"))
       (is (str/includes? md "ten-post"))
       (is (str/includes? md "gov-post-ratify-total="))
       (is (str/includes? md "tenure-gov-post-ratify="))
       (is (str/includes? md "land-grant-executed-total="))
       (is (str/includes? md "gov-flowable / gov-post-ratify:"))
       (is (str/includes? md "tenure-gov-flowable / tenure-gov-post-ratify:"))
       (is (str/includes? md "R2 execute statuses/refused/executed:"))
       (is (str/includes? md "all-r2-not-executed="))
       (is (str/includes? md "Pages deploy"))
       (is (str/includes? md "plan-only"))
       (is (str/includes? md "wrangler-invoked:"))
       (is (str/includes? md "operator runbook"))
       (is (str/includes? md "default refuse"))
       (is (str/includes? md "Pipeline audit summary"))
       (is (str/includes? md "last-run gov-flowable / gov-post-ratify:"))
       (is (str/includes? md "last-run land-grant-executed:"))
       (is (str/includes? md "last-run SS rails-gated / all-rails-gated-refused:"))
       (is (str/includes? md "last-run SS all-r2-not-executed / l0-published:"))
       (is (str/includes? md "last-run SS ladder-to / stage-rails first/second:"))
       (is (str/includes? md "last-run SS stage gated count/all-refused/r2-all-refused:"))
       (is (str/includes? md "last-run SS stage care/mitsuho/hikari gated-admissible:"))
       (is (str/includes? md "last-run SS mitsuho/hikari/care gated-receive admissible:"))
       (is (str/includes? md "last-run SS mitsuho/hikari/care gated-produce admissible:"))
       (is (str/includes? md "SS priority path"))
       (is (str/includes? md "L0 enroll all-seven rails"))
       (is (str/includes? md "enroll-with-all-seven-rails"))
       (is (str/includes? md "all-inkind / liquidity-receive / all-seven-membrane refused:"))
       (is (str/includes? md "L0 held all-seven"))
       (is (str/includes? md "all-seven-membrane / ladder-refused:"))
       (is (str/includes? md "L0 exit→re-affirm stress"))
       (is (str/includes? md "exit state/suspended/ladder-refused:"))
       (is (str/includes? md "L0 falsehood→lift-hold stress"))
       (is (str/includes? md "L0 care-first + mitsuho"))
       (is (str/includes? md "care-first-api-path / before-rails:"))
       (is (str/includes? md "mitsuho-design rail-kind / live-produce / produce-executed:"))
       (is (str/includes? md "L0 care-first + hikari"))
       (is (str/includes? md "hikari-design rail-kind / live-produce / generate-executed:"))
       (is (str/includes? md "L0 care-first + mitsuho + hikari"))
       (is (str/includes? md "mitsuho/hikari design live-produce:"))
       (is (str/includes? md "L0 care+housing multi-gen substrate"))
       (is (str/includes? md "L0 multi-gen substrate + mitsuho+hikari"))
       (is (str/includes? md "held-stress held/all-refused/ladder-refused/land-grant:"))
       (is (str/includes? md "L0 full in-kind substrate"))
       (is (str/includes? md "held-stress held/all-refused/ladder-refused/land-grant/fulfillment/quota:"))
       (is (str/includes? md "L0 vocation recovery"))
       (is (str/includes? md "held-stress held/both-refused/ladder-refused/fulfillment/quota:"))
       (is (str/includes? md "L0 liquidity residual"))
       (is (str/includes? md "held-stress held/receive-refused/ladder-refused/loan/cash:"))
       (is (str/includes? md "held-stress held/membrane/ladder-refused/loan/land-grant:"))
       (is (str/includes? md "L0 all-seven substrate"))
       (is (str/includes? md "L0 offline priority path catalog"))
       (is (str/includes? md "held-stress-embed-count:"))
       (is (str/includes? md "rail-care-iyashi DESIGN"))
       (is (str/includes? md "rail-housing-commons DESIGN"))
       (is (str/includes? md "rail-mitsuho DESIGN"))
       (is (str/includes? md "care-first-mitsuho-path"))
       (is (str/includes? md "rail-hikari DESIGN"))
       (is (str/includes? md "care-first-hikari-path"))
       (is (str/includes? md "rail-tooling-okaimono DESIGN"))
       (is (str/includes? md "rail-compute-murakumo DESIGN"))
       (is (str/includes? md "rail-liquidity-warifu DESIGN"))
       (is (str/includes? md "vocation-recovery-path"))
       (is (str/includes? md "liquidity-residual-path"))
       (is (str/includes? md "rail DESIGN catalog (all-seven discovery)"))
       (is (str/includes? md "live-produce-never"))
       (is (str/includes? md "last-run rail DESIGN catalog rail-count/ok/live-produce-never/all-seven:"))
       (is (str/includes? md "last-run care-first DESIGN mitsuho/hikari live-produce:"))
       (is (str/includes? md "L0 held-stress subjects/ladder-refused="))
       (is (str/includes? md "displacement L0 held-stress subjects / ladder-refused:"))
       (is (str/includes? md "gov held-stress subjects / ladder-refused (L4 rows):"))
       (is (str/includes? md "tenure-gov held-stress subjects / ladder-refused:"))
       (is (str/includes? md "(1) L0 stage/published/token-stub:"))
       (is (str/includes? md "(1) L0 enroll disclosure open/held/may-flow:"))
       (is (str/includes? html "L0 enroll all-seven rails"))
       (is (str/includes? html "L0 held all-seven"))
       (is (str/includes? html "L0 exit→re-affirm"))
       (is (str/includes? html "L0 falsehood→lift-hold"))
       (is (str/includes? html "L0 care-first + mitsuho"))
       (is (str/includes? html "mitsuho-live-produce="))
       (is (str/includes? html "L0 care-first + hikari"))
       (is (str/includes? html "hikari-live-produce="))
       (is (str/includes? html "L0 care-first + mitsuho + hikari"))
       (is (str/includes? html "L0 care+housing multi-gen substrate"))
       (is (str/includes? html "L0 multi-gen substrate + mitsuho+hikari"))
       (is (str/includes? html "held-stress-ladder-refused="))
       (is (str/includes? html "L0 full in-kind substrate"))
       (is (str/includes? html "L0 vocation recovery"))
       (is (str/includes? html "L0 liquidity residual"))
       (is (str/includes? html "L0 all-seven substrate"))
       (is (str/includes? html "L0 offline priority path catalog"))
       (is (str/includes? html "rail-care-iyashi DESIGN"))
       (is (str/includes? html "rail-housing-commons DESIGN"))
       (is (str/includes? html "rail-mitsuho DESIGN"))
       (is (str/includes? html "rail-hikari DESIGN"))
       (is (str/includes? html "rail-tooling-okaimono DESIGN"))
       (is (str/includes? html "rail-compute-murakumo DESIGN"))
       (is (str/includes? html "rail-liquidity-warifu DESIGN"))
       (is (str/includes? html "rail DESIGN catalog (all-seven discovery)"))
       (is (str/includes? html "care-first-mitsuho-path"))
       (is (str/includes? html "care-first-hikari-path"))
       (is (str/includes? html "vocation-recovery-path"))
       (is (str/includes? html "liquidity-residual-path"))
       (is (str/includes? html "live-produce-never="))
       (is (str/includes? md "(1) ladder climb offline:"))
       (is (str/includes? md "rails-hint (care-first for 孫/子)"))
       (is (str/includes? md "stage_sustenance after ladder:"))
       (is (str/includes? md "stage floors care-h/housing-mo"))
       (is (str/includes? md "stage gated-live DESIGN count/admissible/all-refused:"))
       (is (str/includes? md "stage care/mitsuho/hikari gated-admissible:"))
       (is (str/includes? md "ladder-refused="))
       (is (str/includes? md "(3) care/housing DESIGN live-produce / care-first-api (孫/子 first):"))
       (is (str/includes? md "(3) mitsuho/hikari DESIGN live-produce / care-first-api:"))
       (is (str/includes? md "(3) tooling/compute/liquidity DESIGN live-produce / care-first-api:"))
       (is (str/includes? md "(3) all-seven design embed-count / live-produce-never:"))
       (is (str/includes? md "(3) mitsuho R1/gated-admissible/produce-executed:"))
       (is (str/includes? md "(3) mitsuho/hikari gated-receive admissible/phase:"))
       (is (str/includes? md "both-refused="))
       (is (str/includes? md "(3) care-iyashi gated-receive (孫/子) admissible/phase:"))
       (is (str/includes? md "care+mitsuho+hikari-all-refused="))
       (is (str/includes? md "(3) mitsuho/hikari gated-produce admissible/phase:"))
       (is (str/includes? md "full-chain-refused="))
       (is (str/includes? md "(3) care-iyashi gated-produce (孫/子) admissible/phase:"))
       (is (str/includes? md "care+food+energy full-chain-refused="))
       (is (str/includes? md "all-rails-gated-refused"))
       (is (str/includes? md "R2 statuses/executed/all-not-executed:"))
       (is (str/includes? md "R2 food/energy executed:"))
       (is (str/includes? html "liquidity-warifu"))
       (is (str/includes? html "member-principal"))
       (is (str/includes? html "All-disclosure-held stress"))
       (is (str/includes? html "land-grant-executed"))
       (is (str/includes? html "cash-usd-micros"))
       (is (str/includes? html ">g2<"))
       (is (str/includes? html ">earmark<"))
       (is (str/includes? html "L4-flow"))
       (is (str/includes? html "L4-post"))
       (is (str/includes? html "ten-flow"))
       (is (str/includes? html "ten-post"))
       (is (str/includes? html "tenure-gov-post-ratify="))
       (is (str/includes? html "gov-post-ratify-total="))
       (is (str/includes? html "tenure-subjects="))
       (is (str/includes? html "earmark-total="))
       (is (str/includes? html "Pages deploy"))
       (is (str/includes? html "plan-only"))
       (is (str/includes? html "wrangler-invoked="))
       (is (str/includes? html "Pipeline audit summary"))
       (is (str/includes? html "gov-post-ratify="))
       (is (str/includes? html "land-grant-executed="))
       (is (str/includes? html "r2-refused/executed="))
       (is (str/includes? html "all-r2-not-executed="))
       (is (str/includes? html "SS priority path"))
       (is (str/includes? html "care/housing DESIGN live-produce="))
       (is (str/includes? html "mitsuho/hikari DESIGN live-produce="))
       (is (str/includes? html "all-rails-gated-refused="))
       (is (str/includes? html "all-r2-not-executed="))
       (is (str/includes? html "last-run SS rails-gated/all-refused="))
       (is (str/includes? html "ss-all-r2-not-executed="))
       (is (str/includes? html "stage-all-gated-refused="))
       (is (str/includes? html "stage-care/mitsuho/hikari-gated="))
       (is (= :refused (get-in body [:report/pages-deploy-status :phase])))
       (is (false? (get-in body [:report/pages-deploy-status :deployed])))
       (is (false? (get-in body [:report/pages-deploy-status :authorized-to-deploy])))
       (is (false? (get-in body [:report/pages-deploy-status :wrangler-invoked])))
       (is (true? (get-in body [:report/pages-deploy-status :package-ready])))
       (is (map? (get-in body [:report/pages-deploy-status :operator-runbook])))
       (is (false? (get-in body [:report/pages-deploy-status :live])))
       (is (= 0 (get-in body [:report/pages-deploy-status :cash-usd-micros])))
       (let [pkgs (get-in body [:report/displacement-l0 :packages])
             enrolled (filter #(= "offline-enrolled" (:phase %)) pkgs)
             refused (filter #(= "refused" (:phase %)) pkgs)
             dl0 (:report/displacement-l0 body)
             sc (:report/displacement-scorecard body)
             au (:report/pipeline-audit body)]
         (is (seq enrolled))
         (is (seq refused))
         (is (every? true? (map :g2-admissible enrolled)))
         (is (every? false? (map :g2-admissible refused)))
         (is (every? true? (map :funded enrolled)))
         (is (every? false? (map :funded refused)))
         (is (every? pos? (map :earmark-usd-micros-yr enrolled)))
         (is (every? zero? (map :earmark-usd-micros-yr refused)))
         (is (pos? (:earmark-usd-micros-yr dl0)))
         (is (pos? (:committed-usd-micros-yr dl0)))
         (is (pos? (:committed-full-usd-micros-yr dl0)))
         ;; housing held under Council → flowable committed strictly below full book
         (is (every? #(<= (:committed-usd-micros-yr %)
                          (:committed-full-usd-micros-yr %))
                     enrolled))
         (is (some #(< (:committed-usd-micros-yr %)
                       (:committed-full-usd-micros-yr %))
                   enrolled))
         (is (< (:committed-usd-micros-yr dl0)
                (:committed-full-usd-micros-yr dl0)))
         (is (pos? (:gov-flowable-usd-micros dl0)))
         (is (pos? (:gov-post-ratify-usd-micros dl0)))
         ;; post-ratify plan books housing; still >= flowable; land-grant never executed
         (is (>= (:gov-post-ratify-usd-micros dl0)
                 (:gov-flowable-usd-micros dl0)))
         (is (zero? (or (:housing-land-grant-executed dl0) 0)))
         (is (every? zero? (map #(or (:housing-land-grant-executed %) 0) pkgs)))
         (is (pos? (:tenure-gov-post-ratify-usd-micros dl0)))
         (is (= (count enrolled) (:g2-admissible-cohorts dl0)))
         (is (pos? (:tenure-subjects dl0)))
         (is (pos? (:tenure-g2-cohorts dl0)))
         (is (pos? (:tenure-committed-usd-micros-yr dl0)))
         (is (pos? (:tenure-gov-flowable-usd-micros dl0)))
         (is (every? #(= "tenure-offline" (:tenure-phase %)) enrolled))
         (is (every? pos? (map :tenure-subjects enrolled)))
         (is (every? pos? (map :gov-post-ratify-usd-micros enrolled)))
         (is (every? pos? (map :tenure-gov-post-ratify-usd-micros enrolled)))
         (is (pos? (or (:scorecard/gov-post-ratify-committed-usd-micros sc) 0)))
         (is (pos? (or (:scorecard/tenure-gov-post-ratify-committed-usd-micros sc) 0)))
         (is (zero? (or (:scorecard/housing-land-grant-executed sc) 0)))
         (is (pos? (or (:scorecard/r2-status-count sc) 0)))
         (is (pos? (or (:scorecard/r2-refused sc) 0)))
         (is (zero? (or (:scorecard/r2-executed sc) 0)))
         (is (true? (boolean (:scorecard/all-r2-not-executed sc true))))
         ;; pipeline audit on public surface (last-run post-ratify / land-grant=false)
         (is (map? au))
         (is (true? (boolean (:all-runs-live-refused au true))))
         (is (false? (boolean (:any-land-grant-executed? au))))
         (is (false? (boolean (:live au))))
         (is (zero? (or (:cash-usd-micros au) 0)))
         (when (pos? (or (:runs au) 0))
           (is (zero? (or (:last-run-housing-land-grant-executed au) 0)))
           (is (>= (or (:last-run-gov-post-ratify-committed-usd-micros au) 0)
                   (or (:last-run-gov-flowable-committed-usd-micros au) 0))))
         ;; SS priority path public facts (L0 + disclosure + mitsuho/hikari gate)
         (let [l7 (:report/l0-all-seven-enroll body)]
           (is (map? l7))
           (is (nil? (:error l7)))
           (is (= "enroll-with-all-seven-rails" (:api l7)))
           (is (true? (:all-seven-rails-receive-membrane-refused l7)))
           (is (true? (:all-inkind-produce-rails-full-chain-refused l7)))
           (is (true? (:liquidity-receive-full-chain-refused l7)))
           (is (true? (:liquidity-member-principal l7)))
           (is (false? (:liquidity-loan-executed l7)))
           (is (zero? (:liquidity-cash-usd-micros l7)))
           (is (false? (:live l7))))
         (let [lh (:report/l0-held-all-seven-enroll body)]
           (is (map? lh))
           (is (nil? (:error lh)))
           (is (true? (:disclosure-held lh)))
           (is (false? (:entitlements-may-flow lh)))
           (is (true? (:all-seven-rails-receive-membrane-refused lh)))
           (is (true? (:ladder-advance-refused lh)))
           (is (false? (:live lh))))
         (let [ex (:report/l0-exit-reaffirm body)]
           (is (map? ex))
           (is (nil? (:error ex)))
           (is (= "exit-suspended" (:exit-state ex)))
           (is (true? (:exit-ladder-refused ex)))
           (is (= "open" (:reaffirm-state ex)))
           (is (false? (:reaffirm-ladder-refused ex)))
           (is (false? (:live ex))))
         (let [fl (:report/l0-falsehood-lift body)]
           (is (map? fl))
           (is (nil? (:error fl)))
           (is (true? (:falsehood-ladder-refused fl)))
           (is (false? (:lift-ladder-refused fl))))
         (let [cf (:report/l0-care-first-mitsuho body)]
           (is (map? cf))
           (is (nil? (:error cf)))
           (is (true? (:care-mitsuho-both-refused cf)))
           (is (false? (:ladder-advance-refused cf)))
           (is (false? (:live cf)))
           (is (= "care-first-mitsuho-path" (:care-first-api-path cf)))
           (is (false? (:mitsuho-live-produce cf)))
           (is (false? (:mitsuho-produce-executed cf)))
           (is (map? (:mitsuho-design cf)))
           (is (= "food-mitsuho" (get-in cf [:mitsuho-design :rail-kind])))
           (is (map? (:held-stress cf)))
           (is (true? (:held-stress-ladder-refused cf))))
         (let [ch (:report/l0-care-first-hikari body)]
           (is (map? ch))
           (is (nil? (:error ch)))
           (is (true? (:care-hikari-both-refused ch)))
           (is (false? (:ladder-advance-refused ch)))
           (is (= "care-first-hikari-path" (:care-first-api-path ch)))
           (is (false? (:hikari-live-produce ch)))
           (is (false? (:hikari-generate-executed ch)))
           (is (map? (:hikari-design ch)))
           (is (map? (:held-stress ch)))
           (is (true? (:held-stress-ladder-refused ch))))
         (let [cfh (:report/l0-care-first-mitsuho-hikari body)]
           (is (map? cfh))
           (is (nil? (:error cfh)))
           (is (true? (:care-mitsuho-hikari-all-refused cfh)))
           (is (true? (:mitsuho-hikari-both-refused cfh)))
           (is (false? (:ladder-advance-refused cfh)))
           (is (false? (:live cfh)))
           (is (zero? (:cash-usd-micros cfh)))
           (is (false? (:mitsuho-live-produce cfh)))
           (is (false? (:hikari-live-produce cfh)))
           (is (map? (:held-stress cfh)))
           (is (true? (:held-stress-ladder-refused cfh)))
           (is (true? (:held-stress-all-refused cfh))))
         (let [chs (:report/l0-care-housing-first body)]
           (is (map? chs))
           (is (nil? (:error chs)))
           (is (true? (:care-housing-both-refused chs)))
           (is (false? (:land-grant-executed chs)))
           (is (false? (:live chs)))
           (is (map? (:held-stress chs)))
           (is (true? (:held-stress-ladder-refused chs)))
           (is (true? (:held-stress-both-refused chs))))
         (let [mgs (:report/l0-multi-gen-substrate body)]
           (is (map? mgs))
           (is (nil? (:error mgs)))
           (is (true? (:care-housing-mitsuho-hikari-all-refused mgs)))
           (is (true? (:care-housing-both-refused mgs)))
           (is (true? (:mitsuho-hikari-both-refused mgs)))
           (is (false? (:land-grant-executed mgs)))
           (is (false? (:ladder-advance-refused mgs)))
           (is (false? (:live mgs)))
           (is (zero? (:cash-usd-micros mgs))))
         (let [fis (:report/l0-full-inkind-substrate body)]
           (is (map? fis))
           (is (nil? (:error fis)))
           (is (true? (:all-inkind-produce-rails-full-chain-refused fis)))
           (is (true? (:tooling-compute-both-refused fis)))
           (is (false? (:land-grant-executed fis)))
           (is (false? (:fulfillment-executed fis)))
           (is (false? (:quota-executed fis)))
           (is (false? (:ladder-advance-refused fis)))
           (is (false? (:live fis)))
           (is (zero? (:cash-usd-micros fis))))
         (let [voc (:report/l0-vocation-recovery body)]
           (is (map? voc))
           (is (nil? (:error voc)))
           (is (true? (:tooling-compute-both-refused voc)))
           (is (false? (:fulfillment-executed voc)))
           (is (false? (:quota-executed voc)))
           (is (false? (:ladder-advance-refused voc)))
           (is (false? (:live voc)))
           (is (zero? (:cash-usd-micros voc))))
         (let [liq (:report/l0-liquidity-residual body)]
           (is (map? liq))
           (is (nil? (:error liq)))
           (is (true? (:liquidity-receive-full-chain-refused liq)))
           (is (true? (:liquidity-member-principal liq)))
           (is (false? (:liquidity-loan-executed liq)))
           (is (zero? (:liquidity-cash-usd-micros liq)))
           (is (false? (:ladder-advance-refused liq)))
           (is (false? (:live liq)))
           (is (zero? (:cash-usd-micros liq))))
         (let [a7s (:report/l0-all-seven-substrate body)]
           (is (map? a7s))
           (is (nil? (:error a7s)))
           (is (true? (:all-seven-rails-receive-membrane-refused a7s)))
           (is (true? (:all-inkind-produce-rails-full-chain-refused a7s)))
           (is (false? (:liquidity-loan-executed a7s)))
           (is (false? (:land-grant-executed a7s)))
           (is (false? (:ladder-advance-refused a7s)))
           (is (false? (:live a7s)))
           (is (zero? (:cash-usd-micros a7s))))
         (let [cat (:report/l0-priority-path-catalog body)]
           (is (map? cat))
           (is (nil? (:error cat)))
           (is (pos? (or (:path-count cat) 0)))
           (is (some #(= "all-seven-substrate" (:id %)) (:paths cat)))
           (is (false? (:live cat)))
           (is (zero? (:cash-usd-micros cat))))
         (let [rc (:report/rail-care-design body)]
           (is (map? rc))
           (is (nil? (:error rc)))
           (is (= "care-iyashi" (:rail-kind rc)))
           (is (= "care-housing-first-path" (:care-first-api-path rc)))
           (is (= 1 (:care-first-order-rank rc)))
           (is (true? (:multi-gen-first rc)))
           (is (false? (:care-delivery-executed rc)))
           (is (false? (:live rc)))
           (is (zero? (:cash-usd-micros rc)))
           (is (= [] (:score-surface rc))))
         (let [rho (:report/rail-housing-design body)]
           (is (map? rho))
           (is (nil? (:error rho)))
           (is (= "housing-commons" (:rail-kind rho)))
           (is (= "care-housing-first-path" (:care-first-api-path rho)))
           (is (= 2 (:care-first-order-rank rho)))
           (is (= ["care"] (:care-first-before-rails rho)))
           (is (false? (:land-grant-executed rho)))
           (is (false? (:live rho)))
           (is (zero? (:cash-usd-micros rho)))
           (is (= [] (:score-surface rho))))
         (let [rm (:report/rail-mitsuho-design body)]
           (is (map? rm))
           (is (nil? (:error rm)))
           (is (= "food-mitsuho" (:rail-kind rm)))
           (is (= "care-first-mitsuho-path" (:care-first-api-path rm)))
           (is (= ["care" "housing"] (:care-first-before-rails rm)))
           (is (false? (:live-produce rm)))
           (is (false? (:produce-executed rm)))
           (is (false? (:live rm)))
           (is (zero? (:cash-usd-micros rm)))
           (is (= [] (:score-surface rm))))
         (let [rh (:report/rail-hikari-design body)]
           (is (map? rh))
           (is (nil? (:error rh)))
           (is (= "energy-hikari" (:rail-kind rh)))
           (is (= "care-first-hikari-path" (:care-first-api-path rh)))
           (is (= ["care" "housing"] (:care-first-before-rails rh)))
           (is (false? (:live-produce rh)))
           (is (false? (:generate-executed rh)))
           (is (false? (:live rh)))
           (is (zero? (:cash-usd-micros rh)))
           (is (= [] (:score-surface rh))))
         (let [rt (:report/rail-tooling-design body)]
           (is (map? rt))
           (is (nil? (:error rt)))
           (is (= "tooling-okaimono" (:rail-kind rt)))
           (is (= "vocation-recovery-path" (:care-first-api-path rt)))
           (is (true? (:vocation-recovery rt)))
           (is (false? (:fulfillment-executed rt)))
           (is (false? (:live rt)))
           (is (zero? (:cash-usd-micros rt))))
         (let [rco (:report/rail-compute-design body)]
           (is (map? rco))
           (is (nil? (:error rco)))
           (is (= "compute-murakumo" (:rail-kind rco)))
           (is (false? (:quota-executed rco)))
           (is (false? (:live rco)))
           (is (zero? (:cash-usd-micros rco))))
         (let [rl (:report/rail-liquidity-design body)]
           (is (map? rl))
           (is (nil? (:error rl)))
           (is (= "liquidity-warifu" (:rail-kind rl)))
           (is (true? (:member-principal rl)))
           (is (false? (:loan-executed rl)))
           (is (false? (:live rl)))
           (is (zero? (:cash-usd-micros rl))))
         (let [rcat (:report/rail-design-catalog body)]
           (is (map? rcat))
           (is (nil? (:error rcat)))
           (is (= 7 (:rail-count rcat)))
           (is (= 7 (:ok-count rcat)))
           (is (true? (:live-produce-never rcat)))
           (is (true? (:all-cash-zero rcat)))
           (is (true? (:all-live-false rcat)))
           (is (false? (:live rcat)))
           (is (zero? (:cash-usd-micros rcat))))
         (let [sp (:report/ss-priority-path body)]
           (is (map? sp))
           (is (nil? (:error sp)))
           (is (= "L0" (:l0-stage sp)))
           (is (false? (:l0-published sp)))
           (is (some? (:l0-token-stub sp)))
           (is (= "open" (:l0-disclosure-state sp)))
           (is (false? (:l0-disclosure-held sp)))
           (is (true? (:l0-entitlements-may-flow sp)))
           (is (= "l0-enroll-offline" (:l0-path sp)))
           (is (= "L0" (:ladder-from sp)))
           (is (= "L4" (:ladder-to sp)))
           (is (= 4 (:ladder-steps sp)))
           (is (= "care" (:ladder-rails-hint-first sp)))
           (is (false? (:ladder-published sp)))
           (is (true? (:held-stress-ladder-refused sp)))
           (is (false? (:care-live-produce sp)))
           (is (false? (:housing-live-produce sp)))
           (is (= "care-housing-first-path" (:care-care-first-api-path sp)))
           (is (= "care-housing-first-path" (:housing-care-first-api-path sp)))
           (is (= 1 (:care-care-first-order-rank sp)))
           (is (= 2 (:housing-care-first-order-rank sp)))
           (is (= "care-iyashi" (:care-design-rail-kind sp)))
           (is (= "housing-commons" (:housing-design-rail-kind sp)))
           (is (false? (:mitsuho-live-produce sp)))
           (is (false? (:hikari-live-produce sp)))
           (is (= "care-first-mitsuho-path" (:mitsuho-care-first-api-path sp)))
           (is (= "care-first-hikari-path" (:hikari-care-first-api-path sp)))
           (is (= "food-mitsuho" (:mitsuho-design-rail-kind sp)))
           (is (= "energy-hikari" (:hikari-design-rail-kind sp)))
           (is (false? (:tooling-live-produce sp)))
           (is (false? (:compute-live-produce sp)))
           (is (false? (:liquidity-live-produce sp)))
           (is (= "vocation-recovery-path" (:tooling-care-first-api-path sp)))
           (is (= "vocation-recovery-path" (:compute-care-first-api-path sp)))
           (is (= "liquidity-residual-path" (:liquidity-care-first-api-path sp)))
           (is (= "tooling-okaimono" (:tooling-design-rail-kind sp)))
           (is (= "compute-murakumo" (:compute-design-rail-kind sp)))
           (is (= "liquidity-warifu" (:liquidity-design-rail-kind sp)))
           (is (= 7 (:all-seven-design-embed-count sp)))
           (is (true? (:all-seven-design-live-produce-never sp)))
           (is (= "L4" (:stage-sustenance-stage sp)))
           (is (= "care" (:stage-rails-first sp)))
           (is (= "housing" (:stage-rails-second sp)))
           (is (pos? (:stage-care-hours-floor-yr sp)))
           (is (pos? (:stage-housing-months-floor-yr sp)))
           (is (false? (:stage-land-grant-executed sp)))
           (is (true? (:stage-r2-all-refused sp)))
           (is (true? (:stage-all-gated-refused sp)))
           (is (pos? (:stage-gated-count sp)))
           (is (false? (:stage-care-gated-admissible sp)))
           (is (false? (:stage-mitsuho-gated-admissible sp)))
           (is (false? (:stage-hikari-gated-admissible sp)))
           (is (= "open" (:disclosure-state sp)))
           (is (true? (:entitlements-may-flow? sp)))
           (is (true? (:held-stress-held? sp)))
           (is (= "refused" (:held-stress-food-phase sp)))
           (is (= "R1-dry" (:mitsuho-r1-phase sp)))
           (is (false? (:mitsuho-gated-admissible sp)))
           (is (false? (:mitsuho-produce-executed sp)))
           (is (false? (:mitsuho-gated-receive-admissible sp)))
           (is (= "R1-dry" (:hikari-r1-phase sp)))
           (is (false? (:hikari-gated-admissible sp)))
           (is (false? (:hikari-gated-receive-admissible sp)))
           (is (true? (:mitsuho-hikari-receive-both-refused sp)))
           (is (false? (:mitsuho-gated-produce-admissible sp)))
           (is (false? (:hikari-gated-produce-admissible sp)))
           (is (true? (:mitsuho-hikari-produce-both-refused sp)))
           (is (true? (:mitsuho-hikari-full-chain-refused sp)))
           (is (false? (:care-gated-receive-admissible sp)))
           (is (true? (:care-mitsuho-hikari-receive-all-refused sp)))
           (is (false? (:care-gated-produce-admissible sp)))
           (is (true? (:care-mitsuho-hikari-produce-all-refused sp)))
           (is (true? (:care-mitsuho-hikari-full-chain-refused sp)))
           (is (false? (:care-gated-admissible sp)))
           (is (false? (:housing-gated-admissible sp)))
           (is (false? (:housing-gated-receive-admissible sp)))
           (is (false? (:housing-gated-produce-admissible sp)))
           (is (true? (:housing-full-chain-refused sp)))
           (is (true? (:care-housing-mitsuho-hikari-receive-all-refused sp)))
           (is (true? (:care-housing-mitsuho-hikari-produce-all-refused sp)))
           (is (true? (:care-housing-mitsuho-hikari-full-chain-refused sp)))
           (is (false? (:housing-land-grant-executed sp)))
           (is (false? (:tooling-gated-admissible sp)))
           (is (false? (:tooling-gated-receive-admissible sp)))
           (is (false? (:tooling-gated-produce-admissible sp)))
           (is (true? (:tooling-full-chain-refused sp)))
           (is (false? (:compute-gated-admissible sp)))
           (is (false? (:compute-gated-receive-admissible sp)))
           (is (false? (:compute-gated-produce-admissible sp)))
           (is (true? (:compute-full-chain-refused sp)))
           (is (true? (:tooling-compute-full-chain-refused sp)))
           (is (true? (:all-inkind-produce-rails-full-chain-refused sp)))
           (is (false? (:liquidity-gated-admissible sp)))
           (is (false? (:liquidity-gated-receive-admissible sp)))
           (is (true? (:liquidity-receive-full-chain-refused sp)))
           (is (true? (:all-seven-rails-receive-membrane-refused sp)))
           (is (false? (:liquidity-loan-executed sp)))
           (is (zero? (:liquidity-cash-usd-micros sp)))
           (is (= 7 (:rails-gated-count sp)))
           (is (zero? (:rails-gated-admissible-count sp)))
           (is (true? (:all-rails-gated-refused sp)))
           (is (= 7 (:r2-status-count sp)))
           (is (zero? (:r2-executed-count sp)))
           (is (true? (:all-r2-not-executed sp)))
           (is (false? (:r2-food-executed sp)))
           (is (false? (:r2-energy-executed sp)))
           (is (false? (:live sp)))
           (is (zero? (:cash-usd-micros sp)))
           (pp/assert-no-public-scores! (dissoc sp :rail-gated))))
    (is (not (str/includes? md "| rank |")))
    (is (not (re-find #"(?i)percentile" html)))))

(deftest test-html-no-scores
  (let [html (rep/report-html (seed))]
    (is (str/includes? html "public surface"))
    (is (str/includes? html "wellbecoming"))
    (is (str/includes? html "sanae"))
    (is (false? (str/includes? html "priority-rank")))))
