(ns fuchi.methods.test-displacement-l0-path
  (:require [clojure.test :refer [deftest is]]
            [fuchi.methods.displacement-l0-path :as d]
            [fuchi.methods.couple :as couple]
            [fuchi.methods.public-person :as pp]
            ))

(deftest test-funded-event-enrolls
  (let [ev (couple/make-displacement-event
            {:displacing-actor "itonami-robotics"
             :cohort-id "cohort-robotics-remote-2026"
             :displaced-count 48
             :surplus-usd-micros-yr 120000000000
             :funded true})
        pkg (d/run-for-event ev :max-slots 2)]
    (is (= :offline-enrolled (:phase pkg)))
    (is (= 2 (count (:subjects pkg))))
    (is (false? (:live pkg)))
    (is (= 0 (:cash-usd-micros pkg)))
    (is (= [] (:score-surface pkg)))
    (is (true? (get-in pkg [:couple :admissible])))
    (is (= :committed-offline-plan (get-in pkg [:couple :phase])))
    (is (false? (get-in pkg [:couple :commit-live-admissible])))
    (is (pos? (get-in pkg [:couple :committed-usd-micros-yr])))
    (is (pos? (get-in pkg [:couple :headroom-usd-micros-yr])))
    (let [s (first (:subjects pkg))]
      (is (true? (get-in s [:public-person :public-person?])))
      (is (= :dry-produce-plan (get-in s [:food-produce-plan :phase])))
      (is (false? (get-in s [:food-produce-plan :produce-executed])))
      (is (= :dry-produce-plan (get-in s [:care-produce-plan :phase])))
      (is (false? (get-in s [:care-produce-plan :care-delivery-executed])))
      (is (pos? (get-in s [:care-produce-plan :care-hours-floor-yr])))
      (is (= :dry-produce-plan (get-in s [:energy-produce-plan :phase])))
      (is (false? (get-in s [:energy-produce-plan :generate-executed])))
      (is (pos? (get-in s [:energy-produce-plan :kwh-floor-yr])))
      (is (= :dry-produce-plan (get-in s [:housing-produce-plan :phase])))
      (is (false? (get-in s [:housing-produce-plan :land-grant-executed])))
      (is (pos? (get-in s [:housing-produce-plan :housing-months-floor-yr])))
      (is (= :dry-produce-plan (get-in s [:tooling-produce-plan :phase])))
      (is (false? (get-in s [:tooling-produce-plan :fulfillment-executed])))
      (is (pos? (get-in s [:tooling-produce-plan :tool-units-floor-yr])))
      (is (= :dry-produce-plan (get-in s [:compute-produce-plan :phase])))
      (is (false? (get-in s [:compute-produce-plan :quota-executed])))
      (is (pos? (get-in s [:compute-produce-plan :gpu-hours-floor-yr])))
      (is (= "L4" (:stage s)))
      (is (= "L4" (get-in s [:ladder-fact :stage])))
      (is (= "L4" (get-in s [:stage-sustenance :stage])))
      (is (= "care" (first (get-in s [:stage-sustenance :rails]))))
      (is (= "housing" (second (get-in s [:stage-sustenance :rails]))))
      (is (some #{"housing"} (get-in s [:stage-sustenance :rails])))
      (is (some #{"tooling"} (get-in s [:stage-sustenance :rails])))
      (is (some #{"compute"} (get-in s [:stage-sustenance :rails])))
      (is (= :open (get-in s [:disclosure-hold :state])))
      (is (= :open (:disclosure-state s)))
      (is (false? (:disclosure-held? s)))
      (is (true? (:entitlements-may-flow? s)))
      (is (false? (get-in s [:disclosure-continuity :held?])))
      ;; L0 enroll scaffold reused (priority 1+2)
      (is (map? (:l0 s)))
      (is (= :open (get-in s [:l0 :disclosure-state])))
      (is (true? (get-in s [:l0 :entitlements-may-flow?])))
      (is (map? (get-in s [:l0 :disclosure-hold])))
      (is (= "l0-enroll-offline" (get-in s [:l0 :path])))
      (is (= :R1-dry (get-in s [:food-package :phase])))
      (is (= :refused (get-in s [:food-gated-live-status :phase])))
      (is (false? (get-in s [:food-gated-live-status :admissible])))
      (is (false? (get-in s [:food-gated-live-status :produce-executed])))
      (is (= :R1-dry (get-in s [:energy-package :phase])))
      (is (= :refused (get-in s [:energy-gated-live-status :phase])))
      (is (false? (get-in s [:energy-gated-live-status :admissible])))
      (is (= :R1-dry (get-in s [:care-package :phase])))
      (is (= :refused (get-in s [:care-gated-live-status :phase])))
      (is (false? (get-in s [:care-gated-live-status :admissible])))
      (is (false? (get-in s [:care-gated-live-status :care-delivery-executed])))
      (is (= :R1-dry (get-in s [:housing-package :phase])))
      (is (= :refused (get-in s [:housing-gated-live-status :phase])))
      (is (false? (get-in s [:housing-gated-live-status :admissible])))
      (is (false? (get-in s [:housing-gated-live-status :land-grant-executed])))
      (is (false? (:land-grant-executed s)))
      (is (= :R1-dry (get-in s [:tooling-package :phase])))
      (is (= :refused (get-in s [:tooling-gated-live-status :phase])))
      (is (false? (get-in s [:tooling-gated-live-status :fulfillment-executed])))
      (is (= :R1-dry (get-in s [:compute-package :phase])))
      (is (= :refused (get-in s [:compute-gated-live-status :phase])))
      (is (false? (get-in s [:compute-gated-live-status :quota-executed])))
      ;; R1→gated-receive/produce DESIGN membranes (default refuse; robotics L0 path)
      (is (= :refused (get-in s [:food-gated-receive-status :phase])))
      (is (false? (get-in s [:food-gated-receive-status :admissible])))
      (is (= :refused (get-in s [:food-gated-produce-status :phase])))
      (is (false? (get-in s [:food-gated-produce-status :produce-executed])))
      (is (= :refused (get-in s [:care-gated-receive-status :phase])))
      (is (false? (get-in s [:care-gated-produce-status :care-delivery-executed])))
      (is (= :refused (get-in s [:housing-gated-receive-status :phase])))
      (is (false? (get-in s [:housing-gated-produce-status :land-grant-executed])))
      (is (= :refused (get-in s [:tooling-gated-receive-status :phase])))
      (is (false? (get-in s [:tooling-gated-produce-status :fulfillment-executed])))
      (is (= :refused (get-in s [:compute-gated-receive-status :phase])))
      (is (false? (get-in s [:compute-gated-produce-status :quota-executed])))
      ;; liquidity residual (member-principal; no produce plan; loan never invoked)
      (is (= :R1-dry (get-in s [:liquidity-package :phase])))
      (is (true? (get-in s [:liquidity-package :member-principal])))
      (is (zero? (get-in s [:liquidity-package :cash-usd-micros])))
      (is (= :refused (get-in s [:liquidity-gated-live-status :phase])))
      (is (false? (get-in s [:liquidity-gated-live-status :admissible])))
      (is (= :refused (get-in s [:liquidity-gated-receive-status :phase])))
      (is (false? (get-in s [:liquidity-gated-receive-status :admissible])))
      (is (false? (get-in s [:liquidity-gated-receive-status :loan-invoked])))
      (is (false? (:liquidity-loan-executed s)))
      (is (zero? (:liquidity-cash-usd-micros s)))
      (is (true? (get-in s [:membrane-summary :mitsuho-hikari-full-chain-refused])))
      (is (true? (get-in s [:membrane-summary :care-housing-mitsuho-hikari-full-chain-refused])))
      (is (true? (get-in s [:membrane-summary :all-inkind-produce-rails-full-chain-refused])))
      (is (true? (get-in s [:membrane-summary :liquidity-receive-full-chain-refused])))
      (is (true? (get-in s [:membrane-summary :all-seven-rails-receive-membrane-refused])))
      (is (true? (get-in s [:membrane-summary :liquidity-member-principal])))
      (is (false? (get-in s [:membrane-summary :liquidity-loan-executed])))
      (is (false? (get-in s [:membrane-summary :live])))
      (is (zero? (get-in s [:membrane-summary :cash-usd-micros])))
      (is (= :refused (get-in s [:r2-execute-status :phase])))
      (is (false? (get-in s [:r2-execute-status :executed])))
      (is (= :booked-offline (get-in s [:booking :phase])))
      (is (pos? (get-in s [:booking :entry-count])))
      (is (false? (get-in s [:booking :write-live-admissible])))
      (is (= 0 (get-in s [:booking :cash-usd-micros])))
      (is (contains? (get-in s [:booking :category-counts]) "care-flow"))
      ;; priority-(2) held-stress embed (stale disclosure → ladder refuse)
      (is (map? (:held-stress s)))
      (is (= "held" (get-in s [:held-stress :disclosure-state])))
      (is (true? (get-in s [:held-stress :disclosure-held])))
      (is (false? (get-in s [:held-stress :entitlements-may-flow])))
      (is (true? (get-in s [:held-stress :ladder-advance-refused])))
      (is (true? (get-in s [:held-stress :all-inkind-produce-rails-full-chain-refused])))
      (is (true? (get-in s [:held-stress :care-housing-mitsuho-hikari-full-chain-refused])))
      (is (true? (get-in s [:held-stress :tooling-compute-both-refused])))
      (is (false? (get-in s [:held-stress :land-grant-executed])))
      (is (false? (get-in s [:held-stress :live])))
      (is (zero? (get-in s [:held-stress :cash-usd-micros])))
      (is (true? (:held-stress-ladder-refused s)))
      (is (true? (:held-stress-all-inkind-refused s)))
      (pp/assert-no-public-scores! (:public-person s))
      (pp/assert-no-public-scores! (dissoc (:membrane-summary s) :note))
      (pp/assert-no-public-scores! (dissoc (:held-stress s) :note :priority-stack)))
    (is (pos? (:held-stress-subjects pkg)))
    (is (pos? (:held-stress-ladder-refused-subjects pkg)))
    (is (true? (:held-stress-all-subjects-refused pkg)))))

(deftest test-held-stress-primary-path-stays-l0
  "When disclosure is stale as primary path, ladder does not climb; membranes refuse."
  (let [s (d/enroll-displaced-subject
           {:subject-did "did:web:etzhayyim.com:displaced:held-primary:w0"
            :cohort-id "cohort-held-primary"
            :displacing-actor "itonami-robotics"
            :disclosure d/STALE-DISC
            :include-held-stress false
            :climb-steps 4})]
    (is (true? (:disclosure-held? s)))
    (is (false? (:entitlements-may-flow? s)))
    (is (= "L0" (:stage s)))
    (is (#{:stopped :refused :noop} (get-in s [:ladder :phase])))
    (is (true? (get-in s [:membrane-summary :all-inkind-produce-rails-full-chain-refused])))
    (is (false? (:live s)))
    (is (zero? (:cash-usd-micros s)))
    (is (nil? (:held-stress s)))))

(deftest test-unfunded-refused
  (let [ev (couple/make-displacement-event
            {:displacing-actor "hataori"
             :cohort-id "cohort-hataori-2026"
             :displaced-count 30
             :surplus-usd-micros-yr 0
             :funded false})
        pkg (d/run-for-event ev)]
    (is (= :refused (:phase pkg)))
    (is (empty? (:subjects pkg)))
    (is (false? (:live pkg)))
    (is (= 0 (:cash-usd-micros pkg)))))

(deftest test-seed-batch
  (let [out (d/run-default-seed :max-slots 2)]
    (is (false? (:live out)))
    (is (= 0 (:cash-usd-micros out)))
    (is (pos? (:admissible-cohorts out)))
    (is (pos? (:refused-cohorts out)))
    (is (pos? (:enrolled-subjects out)))
    (is (= [] (:score-surface out)))
    (is (pos? (:held-stress-subjects out)))
    (is (pos? (:held-stress-ladder-refused-subjects out)))
    (is (true? (:held-stress-all-subjects-refused out)))
    (is (= (:enrolled-subjects out) (:held-stress-subjects out)))))
