(ns fuchi.methods.test-displacement-pipeline
  "Pipeline run!/write-all! tests — portable under bb and nbb."
  (:require [clojure.test :refer [deftest is]]
            [clojure.string :as str]
            [fuchi.methods.displacement-pipeline :as pipe]))

#?(:cljs
   (def ^:private fs (js/require "node:fs")))

(defn- path-exists? [p]
  #?(:clj (.exists (java.io.File. (str p)))
     :cljs (.existsSync fs (str p))))

(defn- read-text [p]
  #?(:clj (slurp (str p))
     :cljs (.readFileSync fs (str p) "utf8")))

(deftest test-run-pipeline
  (let [out (pipe/run! :max-slots 1)
        sc (:scorecard out)]
    (is (false? (:live out)))
       (is (= 0 (:cash-usd-micros out)))
       (is (= [] (:score-surface out)))
       (is (true? (:all-live-refused out)))
       (is (pos? (:admissible-cohorts out)))
       (is (pos? (:tenure-subjects out)))
       ;; itonami held-stress: L4 path + tenure carry (no double-count on L4 key)
       (is (pos? (:displacement-held-stress-subjects out)))
       (is (pos? (:displacement-held-stress-ladder-refused out)))
       (is (pos? (:tenure-held-stress-subjects out)))
       (is (pos? (:tenure-held-stress-ladder-refused out)))
       (is (pos? (:tenure-held-stress-carried out)))
       (is (= (:tenure-held-stress-subjects out) (:tenure-held-stress-carried out)))
       (is (pos? (:gov-held-stress-subjects out)))
       (is (pos? (:gov-held-stress-ladder-refused out)))
       (is (pos? (:tenure-gov-held-stress-subjects out)))
       (is (pos? (:tenure-gov-held-stress-ladder-refused out)))
       (is (= (:displacement-held-stress-subjects out) (:gov-held-stress-subjects out)))
       (is (= (:tenure-held-stress-subjects out) (:tenure-gov-held-stress-subjects out)))
       (is (= (:displacement-held-stress-subjects out)
              (:scorecard/displacement-held-stress-subjects sc)))
       (is (map? sc))
       (is (map? (:batch out)))
       (is (map? (:gov-route-counts out)))
       (is (pos? (get-in out [:gov-route-counts "council-lv7"] 0)))
       ;; L4 routes equal L4 enrolled subjects (not double-count tenure)
       (is (= (:scorecard/enrolled-subjects sc)
              (get-in out [:gov-route-counts "council-lv7"] 0)))
       (is (= (:scorecard/tenure-subjects sc)
              (get-in sc [:scorecard/tenure-gov-route-counts "council-lv7"] 0)))
       (is (pos? (:scorecard/gov-flowable-committed-usd-micros sc)))
       (is (pos? (:scorecard/gov-post-ratify-committed-usd-micros sc)))
       (is (< (:scorecard/gov-flowable-committed-usd-micros sc)
              (:scorecard/gov-post-ratify-committed-usd-micros sc)))
       (is (pos? (or (:scorecard/committed-post-ratify-usd-micros-yr sc) 0)))
       (is (pos? (:scorecard/tenure-gov-flowable-committed-usd-micros sc)))
       (is (pos? (:scorecard/tenure-gov-post-ratify-committed-usd-micros sc)))
       (is (pos? (:scorecard/tenure-committed-usd-micros-yr sc)))
       (is (pos? (:scorecard/l4-disclosure-open sc)))
       (is (zero? (:scorecard/l4-disclosure-held sc)))
       ;; top-level package facts (parity with scorecard)
       (is (pos? (:gov-flowable-committed-usd-micros out)))
       (is (pos? (:gov-post-ratify-committed-usd-micros out)))
       (is (>= (:gov-post-ratify-committed-usd-micros out)
               (:gov-flowable-committed-usd-micros out)))
       (is (zero? (:housing-land-grant-executed out)))
       (is (pos? (:housing-council-held out)))
       (is (pos? (:r2-status-count out)))
       (is (pos? (:r2-refused out)))
       (is (zero? (:r2-executed out)))
       (is (true? (:all-r2-not-executed out)))
       (is (map? (:ss-priority-path out)))
       (is (true? (:ss-all-rails-gated-refused out)))
       (is (true? (:ss-all-r2-not-executed out)))
       (is (false? (get-in out [:ss-priority-path :l0-published])))
       (is (= 7 (get-in out [:ss-priority-path :rails-gated-count])))
       (is (= "L4" (:ss-ladder-to out)))
       (is (= "care" (:ss-stage-rails-first out)))
       (is (true? (:ss-stage-all-gated-refused out)))
       (is (true? (:ss-stage-r2-all-refused out)))
       (is (false? (:ss-stage-care-gated-admissible out)))
       (is (false? (:ss-stage-mitsuho-gated-admissible out)))
       (is (false? (:ss-stage-hikari-gated-admissible out)))
       (is (false? (:ss-stage-land-grant-executed out)))
       (is (false? (:ss-mitsuho-gated-receive-admissible out)))
       (is (false? (:ss-hikari-gated-receive-admissible out)))
       (is (false? (:ss-care-gated-receive-admissible out)))
       (is (true? (:ss-mitsuho-hikari-receive-both-refused out)))
       (is (true? (:ss-care-mitsuho-hikari-receive-all-refused out)))
       (is (false? (:ss-mitsuho-gated-produce-admissible out)))
       (is (false? (:ss-hikari-gated-produce-admissible out)))
       (is (true? (:ss-mitsuho-hikari-produce-both-refused out)))
       (is (true? (:ss-mitsuho-hikari-full-chain-refused out)))
       (is (false? (:ss-care-gated-produce-admissible out)))
       (is (true? (:ss-care-mitsuho-hikari-produce-all-refused out)))
       (is (true? (:ss-care-mitsuho-hikari-full-chain-refused out)))
       (is (false? (:ss-housing-gated-receive-admissible out)))
       (is (false? (:ss-housing-gated-produce-admissible out)))
       (is (true? (:ss-housing-full-chain-refused out)))
       (is (true? (:ss-care-housing-mitsuho-hikari-receive-all-refused out)))
       (is (true? (:ss-care-housing-mitsuho-hikari-produce-all-refused out)))
       (is (true? (:ss-care-housing-mitsuho-hikari-full-chain-refused out)))
       (is (false? (:ss-tooling-gated-receive-admissible out)))
       (is (false? (:ss-tooling-gated-produce-admissible out)))
       (is (true? (:ss-tooling-full-chain-refused out)))
       (is (false? (:ss-compute-gated-receive-admissible out)))
       (is (false? (:ss-compute-gated-produce-admissible out)))
       (is (true? (:ss-compute-full-chain-refused out)))
       (is (true? (:ss-tooling-compute-full-chain-refused out)))
       (is (true? (:ss-all-inkind-produce-rails-full-chain-refused out)))
       (is (false? (:ss-liquidity-gated-receive-admissible out)))
       (is (true? (:ss-liquidity-receive-full-chain-refused out)))
       (is (true? (:ss-all-seven-rails-receive-membrane-refused out)))
       (is (= "open" (:ss-l0-disclosure-state out)))
       (is (false? (:ss-l0-disclosure-held out)))
       (is (true? (:ss-l0-entitlements-may-flow out)))
       (is (= "l0-enroll-offline" (:ss-l0-path out)))
       (is (true? (:l0-all-seven-membrane-refused out)))
       (is (true? (:l0-all-seven-all-inkind-refused out)))
       (is (true? (:l0-all-seven-liquidity-receive-refused out)))
       (is (false? (:l0-all-seven-liquidity-loan-executed out)))
       (is (zero? (:l0-all-seven-liquidity-cash-usd-micros out)))
       (is (= "open" (:l0-all-seven-continuity-final-state out)))
       (is (pos? (:l0-all-seven-continuity-held-steps out)))
       (is (= "advanced-offline" (:l0-all-seven-ladder-advance-phase out)))
       (is (false? (:l0-all-seven-ladder-advance-refused out)))
       (is (true? (:l0-held-all-seven-membrane-refused out)))
       (is (true? (:l0-held-all-seven-disclosure-held out)))
       (is (false? (:l0-held-all-seven-entitlements-may-flow out)))
       (is (true? (:l0-held-all-seven-ladder-advance-refused out)))
       (is (= "refused" (:l0-held-all-seven-ladder-advance-phase out)))
       (is (= "exit-suspended" (:l0-exit-state out)))
       (is (true? (:l0-exit-suspended out)))
       (is (false? (:l0-exit-entitlements-may-flow out)))
       (is (true? (:l0-exit-ladder-refused out)))
       (is (= "open" (:l0-reaffirm-state out)))
       (is (false? (:l0-reaffirm-exit-suspended out)))
       (is (true? (:l0-reaffirm-entitlements-may-flow out)))
       (is (= "advanced-offline" (:l0-reaffirm-ladder-phase out)))
       (is (false? (:l0-reaffirm-ladder-refused out)))
       (is (true? (:l0-falsehood-held out)))
       (is (true? (:l0-falsehood-ladder-refused out)))
       (is (= "open" (:l0-lift-state out)))
       (is (= "advanced-offline" (:l0-lift-ladder-phase out)))
       (is (false? (:l0-lift-ladder-refused out)))
       (is (true? (:l0-care-first-both-refused out)))
       (is (= "advanced-offline" (:l0-care-first-ladder-phase out)))
       (is (false? (:l0-care-first-ladder-refused out)))
       (is (true? (:l0-care-first-hikari-both-refused out)))
       (is (false? (:l0-care-first-hikari-ladder-refused out)))
       (is (true? (:l0-care-housing-both-refused out)))
       (is (false? (:l0-care-housing-land-grant-executed out)))
       (is (false? (:l0-care-housing-ladder-refused out)))
       ;; displacement L0 membrane aggregates (parity with scorecard)
       (is (pos? (:displacement-membrane-subjects out)))
       (is (pos? (:displacement-all-inkind-full-chain-refused out)))
       (is (pos? (:displacement-all-seven-receive-membrane-refused out)))
       (is (pos? (:displacement-liquidity-recv-refused out)))
    (is (= (:scorecard/displacement-all-seven-receive-membrane-refused sc)
           (:displacement-all-seven-receive-membrane-refused out)))))

(deftest test-write-all
  (let [out (pipe/write-all! :max-slots 1 :include-public false)]
    (is (path-exists? (get-in out [:paths :md])))
    (is (false? (:deployed out)))
    (is (false? (:live out)))
    (is (false? (:package-ready out)))
    (is (nil? (:public-package out)))
    (is (map? (:audit out)))
    (is (path-exists? (get-in out [:audit :path])))
    (is (true? (get-in out [:audit :event :audit/all-live-refused])))
    (is (zero? (get-in out [:audit :event :audit/housing-land-grant-executed] 0)))
    (is (pos? (get-in out [:audit :event :audit/gov-post-ratify-committed-usd-micros] 0)))
    (is (pos? (get-in out [:audit :event :audit/displacement-membrane-subjects] 0)))
    (is (pos? (get-in out [:audit :event :audit/displacement-all-seven-receive-membrane-refused] 0)))
    (is (pos? (get-in out [:audit :event :audit/displacement-liquidity-recv-refused] 0)))
    (is (map? (:itonami-surplus-ledger out)))
    (is (zero? (or (get-in out [:itonami-surplus-ledger :cash-to-workers-usd-micros]) 0)))
    (is (false? (get-in out [:itonami-surplus-ledger :live])))))

(deftest test-write-all-with-public-package
  (let [out (pipe/write-all! :max-slots 1 :include-public true)
        pkg (:public-package out)
        st (:deploy-status out)]
    (is (false? (:deployed out)))
    (is (false? (:wrangler-invoked out)))
    (is (false? (:live out)))
    (is (= 0 (:cash-usd-micros out)))
    (is (true? (:package-ready out)))
    (is (map? pkg))
    (is (false? (:deployed pkg)))
    (is (= :refused (:phase st)))
    (is (false? (:authorized-to-deploy st)))
    (is (zero? (:housing-land-grant-executed out)))
    (is (pos? (:gov-post-ratify-committed-usd-micros out)))
    (is (path-exists? (:index pkg)))
    (is (path-exists? (:wrangler pkg)))
    (when-let [rb (:deploy-runbook pkg)]
      (is (path-exists? rb)))
    (let [html (read-text (:index pkg))]
      (is (str/includes? html "public surface"))
      (is (str/includes? html "plan-only"))
      (is (str/includes? html "Pipeline audit summary"))
      (is (not (re-find #"(?i)priority-rank" html))))))
